/**
 * The emoji set, self-hosted.
 *
 * ── WHY THIS FILE EXISTS RATHER THAN A CDN SCRIPT TAG ─────────────────────
 *
 * Every off-the-shelf picker (emoji-mart and friends) fetches its dataset from
 * a CDN at runtime, and three properties of this product make that the wrong
 * shape:
 *
 *   The client is an installed PWA. An operator on a Douala–Kribi corridor with
 *   no signal can still open a conversation and type; a picker that needs a
 *   network round-trip before it can draw a grid is a picker that is broken
 *   exactly when the rest of the app is not.
 *
 *   It is multi-tenant and white-label. A third-party request fires from the
 *   tenant's device carrying the tenant's referrer, which is a disclosure they
 *   did not agree to and cannot see.
 *
 *   The CSP in the artifact/app shell allow-lists specific hosts. A dataset
 *   fetch is not a script and would be blocked with no visible error — the
 *   picker would simply stay empty, on some machines and not others.
 *
 * ── AND WHY IT IS A LAZY CHUNK ────────────────────────────────────────────
 *
 * It is still ~30 KB of strings that most sessions never open. Everything here
 * is behind a dynamic `import()` from `emoji-picker.tsx`, so the cost lands on
 * the first person who clicks the smiley and on nobody else. Vite gives it its
 * own chunk because nothing in the eager graph imports it — keep it that way:
 * a static import from a component that renders on mount would silently pull
 * the whole set into the main bundle.
 *
 * ── NO IMAGES, ANYWHERE ───────────────────────────────────────────────────
 *
 * These are code points rendered by the platform's own font. Sprite sheets
 * would be another asset to ship, another thing to version, and would render a
 * Twemoji face next to the system faces the OS keyboard inserts — the same
 * emoji looking like two different emoji in the same bubble.
 */

export type EmojiCategory =
  | "recent"
  | "people"
  | "nature"
  | "food"
  | "activity"
  | "travel"
  | "objects"
  | "symbols"
  | "flags";

export type Emoji = {
  /** The character(s). What is stored, sent and compared. */
  e: string;
  /** Short name, shown on hover and matched on. */
  n: string;
  /** Extra search terms. Matched on, never displayed. */
  k: string[];
  /** True when this glyph accepts a skin-tone modifier. */
  t?: boolean;
};

export const CATEGORY_LABELS: Record<EmojiCategory, string> = {
  recent: "Recently used",
  people: "Smileys & people",
  nature: "Animals & nature",
  food: "Food & drink",
  activity: "Activity",
  travel: "Travel & places",
  objects: "Objects",
  symbols: "Symbols",
  flags: "Flags",
};

/**
 * The five Fitzpatrick modifiers, in the order every platform picker shows
 * them. Index 0 is "no modifier" and is the default — a default of anything
 * else picks a skin tone on the user's behalf, which is not ours to pick.
 */
export const SKIN_TONES = ["", "\u{1F3FB}", "\u{1F3FC}", "\u{1F3FD}", "\u{1F3FE}", "\u{1F3FF}"] as const;
export const SKIN_TONE_LABELS = [
  "Default", "Light", "Medium-light", "Medium", "Medium-dark", "Dark",
] as const;

/**
 * Apply a skin tone to a glyph that takes one.
 *
 * The modifier goes after the BASE code point, which for a multi-code-point
 * emoji is not the same as appending to the string: "👍" is one code point and
 * appends cleanly, while a ZWJ sequence would need the modifier inserted after
 * its first. Only single-code-point glyphs are marked `t: true` below, so the
 * simple form is correct for every one of them — and anything not marked comes
 * back untouched rather than mangled.
 */
export function withSkinTone(emoji: Emoji, toneIndex: number): string {
  const tone = SKIN_TONES[toneIndex] || "";
  if (!tone || !emoji.t) return emoji.e;
  return emoji.e + tone;
}

/**
 * The six on the quick-reaction bar.
 *
 * WhatsApp's own six, and the order is not arbitrary: the first is the one
 * people hit most, and it sits under the thumb on a phone. A tenant does not
 * configure these — a reaction bar that differs per workspace stops being
 * muscle memory.
 */
export const QUICK_REACTIONS = ["👍", "❤️", "😂", "😮", "😢", "🙏"] as const;

/* ── The set ───────────────────────────────────────────────────────────────
 *
 * Curated rather than exhaustive: ~430 glyphs covering what people reach for in
 * a work chat, not all 3,800 in Unicode 15. The full set is ~11x the bytes to
 * ship and makes the grid worse — six screens of scrolling to reach 🙏 — and
 * the search box means anything missing is missing, not merely hard to find.
 * Add to it freely; it is a list, and that is the point.
 */
export const EMOJI: Record<Exclude<EmojiCategory, "recent">, Emoji[]> = {
  people: [
    { e: "😀", n: "grinning", k: ["smile", "happy"] },
    { e: "😃", n: "smiley", k: ["happy", "joy"] },
    { e: "😄", n: "smile", k: ["happy", "laugh"] },
    { e: "😁", n: "grin", k: ["happy"] },
    { e: "😆", n: "laughing", k: ["lol", "haha"] },
    { e: "😅", n: "sweat smile", k: ["relief", "phew"] },
    { e: "😂", n: "joy", k: ["lol", "crying laughing", "haha"] },
    { e: "🤣", n: "rofl", k: ["lol", "rolling"] },
    { e: "😊", n: "blush", k: ["happy", "shy"] },
    { e: "😇", n: "innocent", k: ["angel", "halo"] },
    { e: "🙂", n: "slight smile", k: ["ok"] },
    { e: "🙃", n: "upside down", k: ["irony", "sarcasm"] },
    { e: "😉", n: "wink", k: ["flirt"] },
    { e: "😌", n: "relieved", k: ["calm"] },
    { e: "😍", n: "heart eyes", k: ["love"] },
    { e: "🥰", n: "smiling with hearts", k: ["love", "adore"] },
    { e: "😘", n: "kiss", k: ["love"] },
    { e: "😗", n: "kissing", k: [] },
    { e: "😋", n: "yum", k: ["tasty", "delicious"] },
    { e: "😛", n: "tongue", k: ["cheeky"] },
    { e: "😜", n: "wink tongue", k: ["joke"] },
    { e: "🤪", n: "zany", k: ["crazy", "silly"] },
    { e: "🤨", n: "raised eyebrow", k: ["suspicious", "doubt"] },
    { e: "🧐", n: "monocle", k: ["inspect", "examine"] },
    { e: "🤓", n: "nerd", k: ["geek", "glasses"] },
    { e: "😎", n: "sunglasses", k: ["cool"] },
    { e: "🥳", n: "partying", k: ["celebrate", "birthday"] },
    { e: "😏", n: "smirk", k: ["smug"] },
    { e: "😒", n: "unamused", k: ["meh", "unimpressed"] },
    { e: "😞", n: "disappointed", k: ["sad"] },
    { e: "😔", n: "pensive", k: ["sad", "thoughtful"] },
    { e: "😟", n: "worried", k: ["concern"] },
    { e: "🙁", n: "slight frown", k: ["sad"] },
    { e: "😣", n: "persevere", k: ["struggle"] },
    { e: "😖", n: "confounded", k: ["frustrated"] },
    { e: "😫", n: "tired", k: ["exhausted"] },
    { e: "😩", n: "weary", k: ["tired"] },
    { e: "🥺", n: "pleading", k: ["please", "puppy eyes"] },
    { e: "😢", n: "cry", k: ["sad", "tear"] },
    { e: "😭", n: "sob", k: ["cry", "sad"] },
    { e: "😤", n: "triumph", k: ["huff", "determined"] },
    { e: "😠", n: "angry", k: ["mad"] },
    { e: "😡", n: "rage", k: ["furious", "mad"] },
    { e: "🤬", n: "cursing", k: ["swear", "angry"] },
    { e: "🤯", n: "mind blown", k: ["shocked", "wow"] },
    { e: "😳", n: "flushed", k: ["embarrassed", "surprise"] },
    { e: "🥵", n: "hot", k: ["heat", "sweating"] },
    { e: "🥶", n: "cold", k: ["freezing"] },
    { e: "😱", n: "scream", k: ["shock", "fear"] },
    { e: "😨", n: "fearful", k: ["scared"] },
    { e: "😰", n: "anxious", k: ["nervous", "sweat"] },
    { e: "😥", n: "sad relieved", k: ["phew"] },
    { e: "😓", n: "downcast sweat", k: ["stress"] },
    { e: "🤗", n: "hugging", k: ["hug", "welcome"] },
    { e: "🤔", n: "thinking", k: ["hmm", "consider"] },
    { e: "🤭", n: "hand over mouth", k: ["oops", "giggle"] },
    { e: "🤫", n: "shushing", k: ["quiet", "secret"] },
    { e: "🤥", n: "lying", k: ["pinocchio"] },
    { e: "😶", n: "no mouth", k: ["speechless"] },
    { e: "😐", n: "neutral", k: ["meh"] },
    { e: "😑", n: "expressionless", k: ["blank"] },
    { e: "😬", n: "grimacing", k: ["awkward", "eek"] },
    { e: "🙄", n: "eye roll", k: ["whatever"] },
    { e: "😴", n: "sleeping", k: ["zzz", "tired"] },
    { e: "🤤", n: "drooling", k: ["want"] },
    { e: "😪", n: "sleepy", k: ["tired"] },
    { e: "😵", n: "dizzy", k: ["knocked out"] },
    { e: "🤐", n: "zipper mouth", k: ["quiet", "secret"] },
    { e: "🥴", n: "woozy", k: ["drunk", "confused"] },
    { e: "🤢", n: "nauseated", k: ["sick"] },
    { e: "🤮", n: "vomiting", k: ["sick"] },
    { e: "🤧", n: "sneezing", k: ["sick", "cold"] },
    { e: "😷", n: "mask", k: ["sick", "covid"] },
    { e: "🤒", n: "thermometer", k: ["sick", "fever"] },
    { e: "🤕", n: "head bandage", k: ["hurt", "injury"] },
    { e: "🤑", n: "money mouth", k: ["rich", "cash"] },
    { e: "🤠", n: "cowboy", k: ["hat"] },
    { e: "😈", n: "devil", k: ["mischief"] },
    { e: "👿", n: "angry devil", k: ["imp"] },
    { e: "💀", n: "skull", k: ["dead"] },
    { e: "👻", n: "ghost", k: ["halloween"] },
    { e: "👽", n: "alien", k: ["ufo"] },
    { e: "🤖", n: "robot", k: ["bot", "ai"] },
    { e: "💩", n: "poop", k: ["rubbish"] },
    { e: "👋", n: "wave", k: ["hello", "bye", "hi"], t: true },
    { e: "🤚", n: "raised back of hand", k: [], t: true },
    { e: "✋", n: "raised hand", k: ["stop", "high five"], t: true },
    { e: "🖐️", n: "hand splayed", k: [], t: true },
    { e: "👌", n: "ok hand", k: ["perfect", "fine"], t: true },
    { e: "🤌", n: "pinched fingers", k: ["italian"], t: true },
    { e: "🤏", n: "pinching", k: ["small", "little"], t: true },
    { e: "✌️", n: "victory", k: ["peace", "two"], t: true },
    { e: "🤞", n: "crossed fingers", k: ["luck", "hope"], t: true },
    { e: "🤟", n: "love you", k: [], t: true },
    { e: "🤘", n: "rock on", k: ["horns"], t: true },
    { e: "🤙", n: "call me", k: ["shaka"], t: true },
    { e: "👈", n: "point left", k: [], t: true },
    { e: "👉", n: "point right", k: ["this"], t: true },
    { e: "👆", n: "point up", k: ["above"], t: true },
    { e: "👇", n: "point down", k: ["below"], t: true },
    { e: "☝️", n: "index up", k: ["one", "wait"], t: true },
    { e: "👍", n: "thumbs up", k: ["ok", "yes", "agree", "like", "approve"], t: true },
    { e: "👎", n: "thumbs down", k: ["no", "disagree", "dislike"], t: true },
    { e: "✊", n: "raised fist", k: ["power"], t: true },
    { e: "👊", n: "fist bump", k: ["punch"], t: true },
    { e: "👏", n: "clap", k: ["applause", "well done", "bravo"], t: true },
    { e: "🙌", n: "raised hands", k: ["celebrate", "praise"], t: true },
    { e: "👐", n: "open hands", k: ["hug"], t: true },
    { e: "🤲", n: "palms up", k: ["pray", "please"], t: true },
    { e: "🤝", n: "handshake", k: ["deal", "agreement", "partner"] },
    { e: "🙏", n: "folded hands", k: ["please", "thanks", "pray", "thank you"], t: true },
    { e: "💪", n: "flex", k: ["strong", "muscle"], t: true },
    { e: "🦾", n: "mechanical arm", k: ["prosthetic"] },
    { e: "✍️", n: "writing", k: ["sign", "note"], t: true },
    { e: "👀", n: "eyes", k: ["look", "watching", "see"] },
    { e: "🧠", n: "brain", k: ["smart", "think"] },
    { e: "👶", n: "baby", k: ["infant"], t: true },
    { e: "🧒", n: "child", k: ["kid"], t: true },
    { e: "👦", n: "boy", k: [], t: true },
    { e: "👧", n: "girl", k: [], t: true },
    { e: "🧑", n: "person", k: ["adult"], t: true },
    { e: "👨", n: "man", k: [], t: true },
    { e: "👩", n: "woman", k: [], t: true },
    { e: "🧓", n: "older person", k: ["elder"], t: true },
    { e: "👮", n: "police", k: ["officer", "cop"], t: true },
    { e: "👷", n: "construction worker", k: ["builder", "site"], t: true },
    { e: "💂", n: "guard", k: [], t: true },
    { e: "🕵️", n: "detective", k: ["spy", "investigate"], t: true },
    { e: "👨‍💼", n: "office worker", k: ["business", "manager"] },
    { e: "👩‍💼", n: "office worker", k: ["business", "manager"] },
    { e: "👨‍🔧", n: "mechanic", k: ["engineer", "repair"] },
    { e: "👩‍🔧", n: "mechanic", k: ["engineer", "repair"] },
    { e: "👨‍✈️", n: "pilot", k: ["captain", "flight"] },
    { e: "👩‍✈️", n: "pilot", k: ["captain", "flight"] },
    { e: "🧑‍⚖️", n: "judge", k: ["law", "court"] },
    { e: "🤵", n: "person in tux", k: ["formal"], t: true },
    { e: "🎅", n: "santa", k: ["christmas"], t: true },
    { e: "🦸", n: "superhero", k: ["hero"], t: true },
    { e: "🧑‍🤝‍🧑", n: "people holding hands", k: ["team", "together"] },
    { e: "🚶", n: "walking", k: ["pedestrian"], t: true },
    { e: "🏃", n: "running", k: ["run", "hurry"], t: true },
    { e: "🧍", n: "standing", k: [], t: true },
    { e: "🤷", n: "shrug", k: ["dunno", "whatever"], t: true },
    { e: "🤦", n: "facepalm", k: ["disbelief", "oh no"], t: true },
    { e: "💁", n: "tipping hand", k: ["info", "sassy"], t: true },
    { e: "🙋", n: "raising hand", k: ["me", "question", "volunteer"], t: true },
    { e: "🙇", n: "bowing", k: ["sorry", "respect"], t: true },
    { e: "💃", n: "dancer", k: ["dance"], t: true },
    { e: "🕺", n: "man dancing", k: ["dance"], t: true },
  ],

  nature: [
    { e: "🐶", n: "dog", k: ["puppy"] },
    { e: "🐱", n: "cat", k: ["kitten"] },
    { e: "🐭", n: "mouse", k: [] },
    { e: "🐹", n: "hamster", k: [] },
    { e: "🐰", n: "rabbit", k: ["bunny"] },
    { e: "🦊", n: "fox", k: [] },
    { e: "🐻", n: "bear", k: [] },
    { e: "🐼", n: "panda", k: [] },
    { e: "🐨", n: "koala", k: [] },
    { e: "🐯", n: "tiger", k: [] },
    { e: "🦁", n: "lion", k: [] },
    { e: "🐮", n: "cow", k: ["cattle"] },
    { e: "🐷", n: "pig", k: [] },
    { e: "🐸", n: "frog", k: [] },
    { e: "🐵", n: "monkey", k: [] },
    { e: "🙈", n: "see no evil", k: ["monkey", "oops"] },
    { e: "🙉", n: "hear no evil", k: ["monkey"] },
    { e: "🙊", n: "speak no evil", k: ["monkey", "quiet"] },
    { e: "🐔", n: "chicken", k: ["hen"] },
    { e: "🐧", n: "penguin", k: [] },
    { e: "🐦", n: "bird", k: [] },
    { e: "🦆", n: "duck", k: [] },
    { e: "🦅", n: "eagle", k: [] },
    { e: "🦉", n: "owl", k: [] },
    { e: "🐺", n: "wolf", k: [] },
    { e: "🐗", n: "boar", k: [] },
    { e: "🐴", n: "horse", k: [] },
    { e: "🦄", n: "unicorn", k: ["magic"] },
    { e: "🐝", n: "bee", k: ["busy"] },
    { e: "🐛", n: "bug", k: ["insect", "defect"] },
    { e: "🦋", n: "butterfly", k: [] },
    { e: "🐌", n: "snail", k: ["slow"] },
    { e: "🐞", n: "ladybug", k: ["bug"] },
    { e: "🐜", n: "ant", k: [] },
    { e: "🦂", n: "scorpion", k: [] },
    { e: "🐢", n: "turtle", k: ["slow"] },
    { e: "🐍", n: "snake", k: [] },
    { e: "🦎", n: "lizard", k: [] },
    { e: "🐙", n: "octopus", k: [] },
    { e: "🦐", n: "shrimp", k: ["prawn"] },
    { e: "🦀", n: "crab", k: [] },
    { e: "🐠", n: "tropical fish", k: ["fish"] },
    { e: "🐟", n: "fish", k: [] },
    { e: "🐬", n: "dolphin", k: [] },
    { e: "🐳", n: "whale", k: [] },
    { e: "🦈", n: "shark", k: [] },
    { e: "🐊", n: "crocodile", k: [] },
    { e: "🐘", n: "elephant", k: [] },
    { e: "🦏", n: "rhino", k: [] },
    { e: "🦒", n: "giraffe", k: [] },
    { e: "🐫", n: "camel", k: ["desert"] },
    { e: "🐐", n: "goat", k: [] },
    { e: "🐑", n: "sheep", k: [] },
    { e: "🐕", n: "dog", k: [] },
    { e: "🌵", n: "cactus", k: ["desert"] },
    { e: "🌲", n: "evergreen", k: ["tree"] },
    { e: "🌳", n: "tree", k: [] },
    { e: "🌴", n: "palm tree", k: ["tropical", "beach"] },
    { e: "🌱", n: "seedling", k: ["growth", "new"] },
    { e: "🌿", n: "herb", k: ["leaf", "plant"] },
    { e: "☘️", n: "shamrock", k: ["luck"] },
    { e: "🍀", n: "four leaf clover", k: ["luck"] },
    { e: "🍁", n: "maple leaf", k: ["autumn"] },
    { e: "🍂", n: "fallen leaves", k: ["autumn"] },
    { e: "🌾", n: "sheaf of rice", k: ["grain", "harvest"] },
    { e: "💐", n: "bouquet", k: ["flowers"] },
    { e: "🌷", n: "tulip", k: ["flower"] },
    { e: "🌹", n: "rose", k: ["flower", "love"] },
    { e: "🌻", n: "sunflower", k: ["flower"] },
    { e: "🌼", n: "blossom", k: ["flower"] },
    { e: "🌸", n: "cherry blossom", k: ["flower", "spring"] },
    { e: "🌞", n: "sun with face", k: ["sunny"] },
    { e: "🌝", n: "full moon face", k: [] },
    { e: "🌙", n: "crescent moon", k: ["night"] },
    { e: "⭐", n: "star", k: ["favourite"] },
    { e: "🌟", n: "glowing star", k: ["sparkle", "excellent"] },
    { e: "✨", n: "sparkles", k: ["magic", "clean", "new"] },
    { e: "⚡", n: "lightning", k: ["fast", "power", "zap"] },
    { e: "🔥", n: "fire", k: ["hot", "lit", "urgent"] },
    { e: "💥", n: "collision", k: ["boom", "explosion"] },
    { e: "❄️", n: "snowflake", k: ["cold", "winter"] },
    { e: "🌊", n: "wave", k: ["sea", "ocean", "water"] },
    { e: "💧", n: "droplet", k: ["water"] },
    { e: "☔", n: "umbrella rain", k: ["rain", "weather"] },
    { e: "☀️", n: "sun", k: ["sunny", "clear"] },
    { e: "⛅", n: "sun behind cloud", k: ["weather"] },
    { e: "☁️", n: "cloud", k: ["weather", "overcast"] },
    { e: "🌧️", n: "rain cloud", k: ["rain", "weather"] },
    { e: "⛈️", n: "thunderstorm", k: ["storm", "weather"] },
    { e: "🌈", n: "rainbow", k: [] },
    { e: "🌍", n: "globe africa", k: ["earth", "world", "africa"] },
    { e: "🌎", n: "globe americas", k: ["earth", "world"] },
    { e: "🌏", n: "globe asia", k: ["earth", "world"] },
  ],

  food: [
    { e: "🍏", n: "green apple", k: ["fruit"] },
    { e: "🍎", n: "apple", k: ["fruit"] },
    { e: "🍐", n: "pear", k: ["fruit"] },
    { e: "🍊", n: "orange", k: ["fruit", "tangerine"] },
    { e: "🍋", n: "lemon", k: ["fruit", "citrus"] },
    { e: "🍌", n: "banana", k: ["fruit"] },
    { e: "🍉", n: "watermelon", k: ["fruit"] },
    { e: "🍇", n: "grapes", k: ["fruit"] },
    { e: "🍓", n: "strawberry", k: ["fruit"] },
    { e: "🫐", n: "blueberries", k: ["fruit"] },
    { e: "🍈", n: "melon", k: ["fruit"] },
    { e: "🍒", n: "cherries", k: ["fruit"] },
    { e: "🍑", n: "peach", k: ["fruit"] },
    { e: "🥭", n: "mango", k: ["fruit", "tropical"] },
    { e: "🍍", n: "pineapple", k: ["fruit", "tropical"] },
    { e: "🥥", n: "coconut", k: ["tropical"] },
    { e: "🥝", n: "kiwi", k: ["fruit"] },
    { e: "🍅", n: "tomato", k: ["vegetable"] },
    { e: "🍆", n: "aubergine", k: ["eggplant", "vegetable"] },
    { e: "🥑", n: "avocado", k: [] },
    { e: "🥦", n: "broccoli", k: ["vegetable"] },
    { e: "🥬", n: "leafy green", k: ["vegetable", "salad"] },
    { e: "🌽", n: "corn", k: ["maize"] },
    { e: "🌶️", n: "chilli", k: ["pepper", "spicy", "hot"] },
    { e: "🥕", n: "carrot", k: ["vegetable"] },
    { e: "🧄", n: "garlic", k: [] },
    { e: "🧅", n: "onion", k: [] },
    { e: "🥔", n: "potato", k: [] },
    { e: "🍠", n: "sweet potato", k: ["yam"] },
    { e: "🥐", n: "croissant", k: ["bread", "pastry"] },
    { e: "🍞", n: "bread", k: ["loaf"] },
    { e: "🥖", n: "baguette", k: ["bread"] },
    { e: "🧀", n: "cheese", k: [] },
    { e: "🥚", n: "egg", k: [] },
    { e: "🍳", n: "cooking", k: ["fried egg", "breakfast"] },
    { e: "🥓", n: "bacon", k: [] },
    { e: "🍔", n: "burger", k: ["hamburger", "fast food"] },
    { e: "🍟", n: "chips", k: ["fries", "fast food"] },
    { e: "🍕", n: "pizza", k: [] },
    { e: "🌭", n: "hot dog", k: [] },
    { e: "🥪", n: "sandwich", k: ["lunch"] },
    { e: "🌮", n: "taco", k: [] },
    { e: "🌯", n: "burrito", k: ["wrap"] },
    { e: "🥗", n: "salad", k: ["healthy"] },
    { e: "🍜", n: "noodles", k: ["ramen", "soup"] },
    { e: "🍲", n: "stew", k: ["pot", "soup"] },
    { e: "🍛", n: "curry", k: ["rice"] },
    { e: "🍚", n: "rice", k: [] },
    { e: "🍣", n: "sushi", k: [] },
    { e: "🍤", n: "fried prawn", k: ["shrimp", "tempura"] },
    { e: "🍗", n: "poultry leg", k: ["chicken"] },
    { e: "🍖", n: "meat", k: ["bone"] },
    { e: "🥩", n: "steak", k: ["meat"] },
    { e: "🍿", n: "popcorn", k: ["cinema", "film"] },
    { e: "🧂", n: "salt", k: [] },
    { e: "🍦", n: "ice cream", k: ["dessert"] },
    { e: "🍩", n: "doughnut", k: ["donut"] },
    { e: "🍪", n: "biscuit", k: ["cookie"] },
    { e: "🎂", n: "birthday cake", k: ["birthday", "celebrate"] },
    { e: "🍰", n: "cake", k: ["dessert"] },
    { e: "🧁", n: "cupcake", k: ["dessert"] },
    { e: "🍫", n: "chocolate", k: [] },
    { e: "🍬", n: "sweet", k: ["candy"] },
    { e: "🍯", n: "honey", k: [] },
    { e: "☕", n: "coffee", k: ["tea", "hot drink", "break"] },
    { e: "🍵", n: "tea", k: ["green tea"] },
    { e: "🧃", n: "juice box", k: ["drink"] },
    { e: "🥤", n: "soft drink", k: ["cup", "soda"] },
    { e: "🍺", n: "beer", k: ["drink", "pint"] },
    { e: "🍻", n: "cheers", k: ["beers", "celebrate"] },
    { e: "🥂", n: "clinking glasses", k: ["celebrate", "toast", "champagne"] },
    { e: "🍷", n: "wine", k: ["drink"] },
    { e: "🥃", n: "whisky", k: ["drink"] },
    { e: "🍾", n: "bottle popping", k: ["champagne", "celebrate"] },
    { e: "🍽️", n: "plate and cutlery", k: ["dinner", "restaurant"] },
  ],

  activity: [
    { e: "⚽", n: "football", k: ["soccer"] },
    { e: "🏀", n: "basketball", k: [] },
    { e: "🏈", n: "american football", k: [] },
    { e: "⚾", n: "baseball", k: [] },
    { e: "🎾", n: "tennis", k: [] },
    { e: "🏐", n: "volleyball", k: [] },
    { e: "🏉", n: "rugby", k: [] },
    { e: "🎱", n: "pool", k: ["billiards", "8 ball"] },
    { e: "🏓", n: "table tennis", k: ["ping pong"] },
    { e: "🏸", n: "badminton", k: [] },
    { e: "🥊", n: "boxing glove", k: ["fight"] },
    { e: "🥋", n: "martial arts", k: ["judo", "karate"] },
    { e: "⛳", n: "golf", k: ["flag in hole"] },
    { e: "🎯", n: "bullseye", k: ["target", "goal", "direct hit"] },
    { e: "🎳", n: "bowling", k: [] },
    { e: "🎮", n: "video game", k: ["gaming", "controller"] },
    { e: "🎲", n: "dice", k: ["game", "chance"] },
    { e: "🧩", n: "puzzle", k: ["jigsaw", "piece"] },
    { e: "🎨", n: "art", k: ["palette", "design"] },
    { e: "🎭", n: "theatre", k: ["drama", "masks"] },
    { e: "🎤", n: "microphone", k: ["sing", "record", "voice"] },
    { e: "🎧", n: "headphones", k: ["listen", "music", "audio"] },
    { e: "🎵", n: "musical note", k: ["music"] },
    { e: "🎶", n: "musical notes", k: ["music"] },
    { e: "🎸", n: "guitar", k: ["music"] },
    { e: "🥁", n: "drum", k: ["music"] },
    { e: "🎺", n: "trumpet", k: ["music"] },
    { e: "🏆", n: "trophy", k: ["win", "award", "champion"] },
    { e: "🥇", n: "gold medal", k: ["first", "win"] },
    { e: "🥈", n: "silver medal", k: ["second"] },
    { e: "🥉", n: "bronze medal", k: ["third"] },
    { e: "🏅", n: "medal", k: ["award"] },
    { e: "🎖️", n: "military medal", k: ["honour"] },
    { e: "🎫", n: "ticket", k: ["entry", "admission"] },
    { e: "🎁", n: "gift", k: ["present", "birthday"] },
    { e: "🎉", n: "party popper", k: ["celebrate", "congrats", "hooray"] },
    { e: "🎊", n: "confetti", k: ["celebrate", "party"] },
    { e: "🎈", n: "balloon", k: ["party", "birthday"] },
    { e: "🎇", n: "sparkler", k: ["fireworks"] },
    { e: "🎆", n: "fireworks", k: ["celebrate"] },
    { e: "🏕️", n: "camping", k: ["tent", "outdoors"] },
    { e: "🎣", n: "fishing", k: ["rod"] },
    { e: "🏊", n: "swimming", k: ["swim"], t: true },
    { e: "🚴", n: "cycling", k: ["bike"], t: true },
    { e: "🏋️", n: "weightlifting", k: ["gym", "lift"], t: true },
    { e: "⛷️", n: "skiing", k: ["snow"] },
    { e: "🧘", n: "meditation", k: ["yoga", "calm"], t: true },
  ],

  travel: [
    { e: "🚗", n: "car", k: ["drive", "vehicle"] },
    { e: "🚕", n: "taxi", k: ["cab"] },
    { e: "🚙", n: "suv", k: ["car", "4x4"] },
    { e: "🚌", n: "bus", k: ["transport"] },
    { e: "🚎", n: "trolleybus", k: [] },
    { e: "🏎️", n: "racing car", k: ["fast"] },
    { e: "🚓", n: "police car", k: [] },
    { e: "🚑", n: "ambulance", k: ["emergency"] },
    { e: "🚒", n: "fire engine", k: ["emergency"] },
    { e: "🚐", n: "minibus", k: ["van"] },
    { e: "🛻", n: "pickup truck", k: ["ute"] },
    { e: "🚚", n: "delivery truck", k: ["lorry", "van", "delivery"] },
    { e: "🚛", n: "articulated lorry", k: ["truck", "haulage", "freight"] },
    { e: "🚜", n: "tractor", k: ["farm"] },
    { e: "🏍️", n: "motorcycle", k: ["bike", "moto"] },
    { e: "🛵", n: "scooter", k: ["moped", "delivery"] },
    { e: "🚲", n: "bicycle", k: ["bike"] },
    { e: "🛴", n: "kick scooter", k: [] },
    { e: "🚨", n: "siren", k: ["emergency", "alert", "urgent"] },
    { e: "🚔", n: "police car front", k: [] },
    { e: "🚍", n: "bus front", k: [] },
    { e: "🚅", n: "bullet train", k: ["train", "fast"] },
    { e: "🚆", n: "train", k: ["rail"] },
    { e: "🚇", n: "metro", k: ["subway", "underground"] },
    { e: "🚉", n: "station", k: ["train"] },
    { e: "🚂", n: "locomotive", k: ["steam train", "rail"] },
    { e: "✈️", n: "aeroplane", k: ["plane", "flight", "air freight"] },
    { e: "🛫", n: "departure", k: ["take off", "flight"] },
    { e: "🛬", n: "arrival", k: ["landing", "flight"] },
    { e: "🛩️", n: "small plane", k: ["aircraft"] },
    { e: "🚁", n: "helicopter", k: [] },
    { e: "🚀", n: "rocket", k: ["launch", "fast", "ship it"] },
    { e: "🛸", n: "flying saucer", k: ["ufo"] },
    { e: "⛵", n: "sailboat", k: ["sailing"] },
    { e: "🚤", n: "speedboat", k: ["boat"] },
    { e: "🛥️", n: "motor boat", k: [] },
    { e: "🛳️", n: "passenger ship", k: ["cruise"] },
    { e: "⛴️", n: "ferry", k: ["boat"] },
    { e: "🚢", n: "ship", k: ["vessel", "sea freight", "cargo"] },
    { e: "⚓", n: "anchor", k: ["port", "harbour", "ship"] },
    { e: "⛽", n: "fuel pump", k: ["petrol", "diesel", "gas"] },
    { e: "🚧", n: "construction", k: ["roadworks", "wip", "barrier"] },
    { e: "🗺️", n: "map", k: ["world", "route"] },
    { e: "🧭", n: "compass", k: ["direction", "navigate"] },
    { e: "🏔️", n: "mountain", k: ["peak", "snow"] },
    { e: "🏖️", n: "beach", k: ["holiday", "sea"] },
    { e: "🏝️", n: "island", k: ["tropical"] },
    { e: "🏜️", n: "desert", k: [] },
    { e: "🌋", n: "volcano", k: [] },
    { e: "🏗️", n: "construction site", k: ["crane", "building"] },
    { e: "🏭", n: "factory", k: ["industry", "plant"] },
    { e: "🏢", n: "office building", k: ["work", "company"] },
    { e: "🏬", n: "department store", k: ["shop"] },
    { e: "🏦", n: "bank", k: ["finance"] },
    { e: "🏥", n: "hospital", k: ["medical"] },
    { e: "🏨", n: "hotel", k: ["accommodation"] },
    { e: "🏫", n: "school", k: ["education"] },
    { e: "🏛️", n: "classical building", k: ["government", "institution", "customs"] },
    { e: "🏠", n: "house", k: ["home"] },
    { e: "🏘️", n: "houses", k: ["neighbourhood"] },
    { e: "🕌", n: "mosque", k: [] },
    { e: "⛪", n: "church", k: [] },
    { e: "🌆", n: "cityscape", k: ["city", "dusk"] },
    { e: "🌉", n: "bridge", k: ["night"] },
    { e: "🗼", n: "tower", k: ["landmark"] },
    { e: "🎡", n: "ferris wheel", k: ["fair"] },
  ],

  objects: [
    { e: "💼", n: "briefcase", k: ["work", "business"] },
    { e: "📦", n: "package", k: ["parcel", "box", "shipment", "cargo"] },
    { e: "📬", n: "mailbox", k: ["post", "mail"] },
    { e: "📮", n: "postbox", k: ["post"] },
    { e: "✉️", n: "envelope", k: ["email", "mail", "letter"] },
    { e: "📧", n: "e-mail", k: ["email", "mail"] },
    { e: "📨", n: "incoming envelope", k: ["mail", "received"] },
    { e: "📩", n: "envelope with arrow", k: ["send", "mail"] },
    { e: "📤", n: "outbox", k: ["send", "sent"] },
    { e: "📥", n: "inbox", k: ["receive"] },
    { e: "📝", n: "memo", k: ["note", "write", "edit"] },
    { e: "📄", n: "page", k: ["document", "file", "paper"] },
    { e: "📃", n: "page with curl", k: ["document"] },
    { e: "📑", n: "bookmark tabs", k: ["index", "pages"] },
    { e: "📊", n: "bar chart", k: ["stats", "report", "analytics"] },
    { e: "📈", n: "chart up", k: ["growth", "increase", "profit"] },
    { e: "📉", n: "chart down", k: ["decline", "loss", "decrease"] },
    { e: "📋", n: "clipboard", k: ["checklist", "copy"] },
    { e: "📅", n: "calendar", k: ["date", "schedule"] },
    { e: "📆", n: "tear-off calendar", k: ["date", "deadline"] },
    { e: "🗓️", n: "spiral calendar", k: ["schedule", "planning"] },
    { e: "📌", n: "pushpin", k: ["pin", "important"] },
    { e: "📍", n: "round pin", k: ["location", "here"] },
    { e: "📎", n: "paperclip", k: ["attach", "attachment"] },
    { e: "🖇️", n: "linked paperclips", k: ["attach", "link"] },
    { e: "📁", n: "folder", k: ["file", "dossier"] },
    { e: "📂", n: "open folder", k: ["file", "dossier"] },
    { e: "🗂️", n: "card index dividers", k: ["organise", "files"] },
    { e: "🗄️", n: "filing cabinet", k: ["archive", "records"] },
    { e: "🗃️", n: "card file box", k: ["archive"] },
    { e: "🗑️", n: "wastebasket", k: ["bin", "delete", "trash"] },
    { e: "📇", n: "card index", k: ["contacts", "rolodex"] },
    { e: "📚", n: "books", k: ["library", "read", "study"] },
    { e: "📖", n: "open book", k: ["read", "manual"] },
    { e: "🔖", n: "bookmark", k: ["save", "tag"] },
    { e: "🏷️", n: "label", k: ["tag", "price"] },
    { e: "💰", n: "money bag", k: ["cash", "budget", "payment"] },
    { e: "💵", n: "banknotes", k: ["cash", "money", "dollar"] },
    { e: "💳", n: "credit card", k: ["payment", "card"] },
    { e: "🧾", n: "receipt", k: ["invoice", "bill", "expense"] },
    { e: "💸", n: "money with wings", k: ["spend", "cost", "expense"] },
    { e: "🏧", n: "atm", k: ["cash machine"] },
    { e: "⚖️", n: "balance scale", k: ["justice", "weight", "legal", "balance"] },
    { e: "📏", n: "ruler", k: ["measure"] },
    { e: "📐", n: "set square", k: ["measure", "geometry"] },
    { e: "✂️", n: "scissors", k: ["cut"] },
    { e: "🖊️", n: "pen", k: ["write", "sign"] },
    { e: "🖋️", n: "fountain pen", k: ["sign", "signature"] },
    { e: "✏️", n: "pencil", k: ["write", "edit", "draft"] },
    { e: "🖍️", n: "crayon", k: ["colour"] },
    { e: "🔍", n: "magnifying glass", k: ["search", "find", "look", "inspect"] },
    { e: "🔎", n: "magnifier right", k: ["search", "zoom"] },
    { e: "🔒", n: "locked", k: ["secure", "private", "closed"] },
    { e: "🔓", n: "unlocked", k: ["open", "access"] },
    { e: "🔐", n: "locked with key", k: ["secure", "encrypted"] },
    { e: "🔑", n: "key", k: ["access", "password"] },
    { e: "🗝️", n: "old key", k: ["access"] },
    { e: "🔨", n: "hammer", k: ["build", "fix", "tool"] },
    { e: "🛠️", n: "tools", k: ["settings", "repair", "maintenance"] },
    { e: "🔧", n: "spanner", k: ["wrench", "fix", "config"] },
    { e: "🔩", n: "nut and bolt", k: ["hardware"] },
    { e: "⚙️", n: "gear", k: ["settings", "config", "cog"] },
    { e: "🧰", n: "toolbox", k: ["tools", "repair"] },
    { e: "🔋", n: "battery", k: ["power", "charge"] },
    { e: "🔌", n: "plug", k: ["power", "electric"] },
    { e: "💡", n: "light bulb", k: ["idea", "suggestion", "tip"] },
    { e: "🔦", n: "torch", k: ["flashlight"] },
    { e: "🕯️", n: "candle", k: ["light"] },
    { e: "📱", n: "mobile phone", k: ["phone", "mobile", "smartphone"] },
    { e: "☎️", n: "telephone", k: ["call", "phone"] },
    { e: "📞", n: "phone receiver", k: ["call", "ring"] },
    { e: "📟", n: "pager", k: [] },
    { e: "📠", n: "fax", k: [] },
    { e: "💻", n: "laptop", k: ["computer", "work"] },
    { e: "🖥️", n: "desktop computer", k: ["monitor", "screen"] },
    { e: "⌨️", n: "keyboard", k: ["type"] },
    { e: "🖨️", n: "printer", k: ["print"] },
    { e: "🖱️", n: "mouse", k: ["click"] },
    { e: "💾", n: "floppy disk", k: ["save"] },
    { e: "💿", n: "disc", k: ["cd"] },
    { e: "📷", n: "camera", k: ["photo", "picture"] },
    { e: "📸", n: "camera flash", k: ["photo", "snap"] },
    { e: "📹", n: "video camera", k: ["record", "video"] },
    { e: "🎥", n: "movie camera", k: ["film", "video"] },
    { e: "📺", n: "television", k: ["tv"] },
    { e: "📻", n: "radio", k: ["broadcast"] },
    { e: "⏰", n: "alarm clock", k: ["time", "reminder", "wake"] },
    { e: "⏱️", n: "stopwatch", k: ["timer", "speed"] },
    { e: "⏳", n: "hourglass", k: ["wait", "time", "pending"] },
    { e: "⌛", n: "hourglass done", k: ["time up", "expired"] },
    { e: "🕐", n: "clock", k: ["time", "hour"] },
    { e: "🔔", n: "bell", k: ["notification", "alert", "reminder"] },
    { e: "🔕", n: "bell crossed", k: ["mute", "silent", "do not disturb"] },
    { e: "📢", n: "loudspeaker", k: ["announcement", "broadcast"] },
    { e: "📣", n: "megaphone", k: ["announce", "shout"] },
    { e: "🔇", n: "muted", k: ["silent"] },
    { e: "🔊", n: "speaker loud", k: ["volume", "sound"] },
    { e: "🎙️", n: "studio microphone", k: ["record", "podcast", "voice"] },
    { e: "🛡️", n: "shield", k: ["security", "protect", "defence"] },
    { e: "🧯", n: "fire extinguisher", k: ["safety", "emergency"] },
    { e: "🪪", n: "identity card", k: ["id", "licence", "badge"] },
    { e: "🧳", n: "luggage", k: ["travel", "suitcase", "baggage"] },
    { e: "🩺", n: "stethoscope", k: ["medical", "health", "check"] },
    { e: "💊", n: "pill", k: ["medicine"] },
    { e: "🧪", n: "test tube", k: ["lab", "experiment", "test"] },
    { e: "🔬", n: "microscope", k: ["science", "inspect", "detail"] },
    { e: "🧲", n: "magnet", k: ["attract"] },
  ],

  symbols: [
    { e: "❤️", n: "red heart", k: ["love", "like"] },
    { e: "🧡", n: "orange heart", k: ["love"] },
    { e: "💛", n: "yellow heart", k: ["love"] },
    { e: "💚", n: "green heart", k: ["love"] },
    { e: "💙", n: "blue heart", k: ["love"] },
    { e: "💜", n: "purple heart", k: ["love"] },
    { e: "🖤", n: "black heart", k: [] },
    { e: "🤍", n: "white heart", k: [] },
    { e: "💔", n: "broken heart", k: ["sad"] },
    { e: "💕", n: "two hearts", k: ["love"] },
    { e: "💯", n: "hundred", k: ["100", "perfect", "agree"] },
    { e: "✅", n: "tick", k: ["check", "done", "yes", "approved", "complete"] },
    { e: "☑️", n: "ballot tick", k: ["check", "done"] },
    { e: "✔️", n: "check mark", k: ["tick", "done", "yes"] },
    { e: "❌", n: "cross", k: ["no", "wrong", "cancel", "fail"] },
    { e: "❎", n: "cross button", k: ["no"] },
    { e: "⭕", n: "circle", k: ["correct", "o"] },
    { e: "🚫", n: "prohibited", k: ["no", "forbidden", "banned"] },
    { e: "⛔", n: "no entry", k: ["stop", "blocked"] },
    { e: "❗", n: "exclamation", k: ["important", "warning", "urgent"] },
    { e: "❓", n: "question", k: ["help", "query"] },
    { e: "❕", n: "white exclamation", k: [] },
    { e: "❔", n: "white question", k: [] },
    { e: "⚠️", n: "warning", k: ["caution", "alert", "careful"] },
    { e: "🔴", n: "red circle", k: ["stop", "blocked", "critical"] },
    { e: "🟠", n: "orange circle", k: ["warning", "at risk"] },
    { e: "🟡", n: "yellow circle", k: ["caution", "pending"] },
    { e: "🟢", n: "green circle", k: ["go", "ok", "on track"] },
    { e: "🔵", n: "blue circle", k: ["info"] },
    { e: "⚫", n: "black circle", k: [] },
    { e: "⚪", n: "white circle", k: [] },
    { e: "🔶", n: "orange diamond", k: [] },
    { e: "🔷", n: "blue diamond", k: [] },
    { e: "▶️", n: "play", k: ["start", "resume"] },
    { e: "⏸️", n: "pause", k: ["hold"] },
    { e: "⏹️", n: "stop", k: [] },
    { e: "⏺️", n: "record", k: [] },
    { e: "⏭️", n: "next track", k: ["skip"] },
    { e: "🔁", n: "repeat", k: ["loop", "again"] },
    { e: "🔄", n: "refresh", k: ["sync", "reload", "update"] },
    { e: "🔀", n: "shuffle", k: ["random"] },
    { e: "⬆️", n: "up arrow", k: ["increase", "above"] },
    { e: "⬇️", n: "down arrow", k: ["decrease", "below"] },
    { e: "⬅️", n: "left arrow", k: ["back", "previous"] },
    { e: "➡️", n: "right arrow", k: ["next", "forward"] },
    { e: "↩️", n: "reply arrow", k: ["back", "return"] },
    { e: "🔝", n: "top", k: ["up"] },
    { e: "🆕", n: "new", k: [] },
    { e: "🆗", n: "ok", k: ["okay"] },
    { e: "🆘", n: "sos", k: ["help", "emergency"] },
    { e: "🆙", n: "up", k: ["upgrade"] },
    { e: "🔜", n: "soon", k: ["later"] },
    { e: "💬", n: "speech balloon", k: ["comment", "chat", "message"] },
    { e: "🗨️", n: "left speech bubble", k: ["say"] },
    { e: "💭", n: "thought balloon", k: ["think", "idea"] },
    { e: "🗯️", n: "anger bubble", k: ["shout"] },
    { e: "♻️", n: "recycle", k: ["environment", "reuse"] },
    { e: "⚜️", n: "fleur de lis", k: [] },
    { e: "🔰", n: "beginner", k: ["new", "learner"] },
    { e: "〽️", n: "part alternation", k: [] },
    { e: "©️", n: "copyright", k: [] },
    { e: "®️", n: "registered", k: ["trademark"] },
    { e: "™️", n: "trademark", k: ["tm"] },
    { e: "#️⃣", n: "hash", k: ["number", "channel"] },
    { e: "*️⃣", n: "asterisk", k: ["star"] },
    { e: "0️⃣", n: "zero", k: ["0"] },
    { e: "1️⃣", n: "one", k: ["1", "first"] },
    { e: "2️⃣", n: "two", k: ["2", "second"] },
    { e: "3️⃣", n: "three", k: ["3", "third"] },
    { e: "4️⃣", n: "four", k: ["4"] },
    { e: "5️⃣", n: "five", k: ["5"] },
  ],

  flags: [
    { e: "🏳️", n: "white flag", k: ["surrender"] },
    { e: "🏴", n: "black flag", k: [] },
    { e: "🏁", n: "chequered flag", k: ["finish", "race", "done"] },
    { e: "🚩", n: "triangular flag", k: ["red flag", "issue", "risk", "blocker"] },
    { e: "🇨🇲", n: "Cameroon", k: ["cm", "cameroun"] },
    { e: "🇨🇩", n: "DR Congo", k: ["cd", "congo", "drc"] },
    { e: "🇨🇬", n: "Congo", k: ["cg", "brazzaville"] },
    { e: "🇬🇦", n: "Gabon", k: ["ga"] },
    { e: "🇬🇶", n: "Equatorial Guinea", k: ["gq"] },
    { e: "🇹🇩", n: "Chad", k: ["td", "tchad"] },
    { e: "🇨🇫", n: "Central African Republic", k: ["cf", "car"] },
    { e: "🇳🇬", n: "Nigeria", k: ["ng"] },
    { e: "🇬🇭", n: "Ghana", k: ["gh"] },
    { e: "🇨🇮", n: "Côte d'Ivoire", k: ["ci", "ivory coast"] },
    { e: "🇸🇳", n: "Senegal", k: ["sn"] },
    { e: "🇧🇯", n: "Benin", k: ["bj"] },
    { e: "🇹🇬", n: "Togo", k: ["tg"] },
    { e: "🇧🇫", n: "Burkina Faso", k: ["bf"] },
    { e: "🇲🇱", n: "Mali", k: ["ml"] },
    { e: "🇳🇪", n: "Niger", k: ["ne"] },
    { e: "🇬🇳", n: "Guinea", k: ["gn"] },
    { e: "🇰🇪", n: "Kenya", k: ["ke"] },
    { e: "🇿🇦", n: "South Africa", k: ["za"] },
    { e: "🇪🇬", n: "Egypt", k: ["eg"] },
    { e: "🇲🇦", n: "Morocco", k: ["ma"] },
    { e: "🇫🇷", n: "France", k: ["fr"] },
    { e: "🇬🇧", n: "United Kingdom", k: ["gb", "uk", "britain"] },
    { e: "🇧🇪", n: "Belgium", k: ["be"] },
    { e: "🇩🇪", n: "Germany", k: ["de"] },
    { e: "🇪🇸", n: "Spain", k: ["es"] },
    { e: "🇮🇹", n: "Italy", k: ["it"] },
    { e: "🇳🇱", n: "Netherlands", k: ["nl", "holland"] },
    { e: "🇵🇹", n: "Portugal", k: ["pt"] },
    { e: "🇺🇸", n: "United States", k: ["us", "usa", "america"] },
    { e: "🇨🇦", n: "Canada", k: ["ca"] },
    { e: "🇧🇷", n: "Brazil", k: ["br"] },
    { e: "🇨🇳", n: "China", k: ["cn"] },
    { e: "🇮🇳", n: "India", k: ["in"] },
    { e: "🇯🇵", n: "Japan", k: ["jp"] },
    { e: "🇦🇪", n: "United Arab Emirates", k: ["ae", "dubai"] },
    { e: "🇹🇷", n: "Türkiye", k: ["tr", "turkey"] },
    { e: "🇸🇬", n: "Singapore", k: ["sg"] },
  ],
};

export const CATEGORY_ORDER: Exclude<EmojiCategory, "recent">[] = [
  "people", "nature", "food", "activity", "travel", "objects", "symbols", "flags",
];

/**
 * Search across every category.
 *
 * Prefix matches on the NAME rank above keyword matches, which is what makes
 * typing "th" reach 👍 (thumbs up) before 🌡️ (thermometer) — people type the
 * first letters of the thing they want, and a picker that rewards a substring
 * match anywhere puts the answer on the third row.
 */
export function searchEmoji(term: string, limit = 60): Emoji[] {
  const q = term.trim().toLowerCase();
  if (!q) return [];
  const exact: Emoji[] = [];
  const prefix: Emoji[] = [];
  const loose: Emoji[] = [];
  for (const category of CATEGORY_ORDER) {
    for (const item of EMOJI[category]) {
      const name = item.n.toLowerCase();
      if (name === q) exact.push(item);
      else if (name.startsWith(q)) prefix.push(item);
      else if (name.includes(q) || item.k.some((k) => k.toLowerCase().includes(q))) loose.push(item);
    }
  }
  return [...exact, ...prefix, ...loose].slice(0, limit);
}

/** Total count — used by the test that guards against a category being emptied
 *  by a bad merge. */
export const EMOJI_COUNT = CATEGORY_ORDER.reduce((n, c) => n + EMOJI[c].length, 0);
