import { tenant } from "./api-client";

export type Role = {
  role_id: string;
  code: string;
  name: string;
  is_system?: boolean;
};
export type Module = {
  module_key: string;
  group_key: string;
  name: string;
  sort_order: number;
};
export type Grant = {
  role_id: string;
  module_key: string;
  can_create: boolean;
  can_read: boolean;
  can_update: boolean;
  can_delete: boolean;
  can_approve: boolean;
  /** 12771 — export is a right over DATA; validate and disburse are the two
   *  decisions maker-checker most wants apart from "approve". */
  can_export: boolean;
  can_validate: boolean;
  can_disburse: boolean;
};

export const PERMS = [
  "can_read",
  "can_create",
  "can_update",
  "can_delete",
  "can_approve",
  // 12771. Order is deliberate: the CRUD four, then the three decisions, so a
  // cell reads left-to-right from "may touch it" to "may release money".
  "can_validate",
  "can_disburse",
  "can_export",
] as const;
export type PermKey = (typeof PERMS)[number];
export const PERM_LABEL: Record<PermKey, string> = {
  can_read: "R",
  can_create: "C",
  can_update: "U",
  can_delete: "D",
  can_approve: "A",
  can_validate: "V",
  can_disburse: "$",
  can_export: "X",
};
export const PERM_TITLE: Record<PermKey, string> = {
  can_read: "Read / view",
  can_create: "Create",
  can_update: "Update / edit",
  can_delete: "Delete",
  can_approve: "Approve",
  can_validate: "Validate — the finance visa, not a signature",
  can_disburse: "Disburse — hand over the cash",
  can_export: "Export — take this module's data out of the building",
};

export const emptyGrant = (role_id: string, module_key: string): Grant => ({
  role_id,
  module_key,
  can_create: false,
  can_read: false,
  can_update: false,
  can_delete: false,
  can_approve: false,
  can_export: false,
  can_validate: false,
  can_disburse: false,
});

export const fetchRoles = () => tenant<Role[]>("/roles");
export const fetchModules = () => tenant<Module[]>("/catalogue/modules");
/**
 * The COMPLETE grant set — not `/permissions`, which paginates at 50.
 *
 * The matrix edits by role×module and PUTs the whole row, so a grant it hasn't
 * loaded is a grant it will overwrite with all-false the moment you touch that
 * cell. With 11 roles × 72 modules the seeded grants alone exceed one page, so
 * loading through the paginated list made edits look like they weren't saving
 * while quietly destroying the grants below the cut.
 */
export const fetchPermissions = () => tenant<Grant[]>("/permissions/matrix");
/**
 * Upsert one role x module grant.
 *
 * F-GAP-11 — WHY THE BODY IS SPELLED OUT INSTEAD OF SPREAD.
 *
 * `body: g` sent whatever was on the object, and what was on the object was a
 * full database row. `/permissions/matrix` returns `RETURNING *`, so every grant
 * the matrix loads carries `permission_id`; the `Grant` annotation is erased at
 * runtime and does not strip it. The server validator is `.strict()` — rightly,
 * because a misspelled `can_aprove` silently written as `false` is a privilege
 * change nobody asked for — so it answered 422 "Unrecognized key(s) in object:
 * 'permission_id'" and the matrix could not save any cell that already had a
 * grant. Which is to say: the screen you fix permissions on could not be used to
 * fix permissions.
 *
 * A virgin cell DID save, because `emptyGrant()` builds a clean object — and
 * then the response (also `RETURNING *`) was stored in state, so the SECOND
 * toggle of that same cell failed. Save once, then never again.
 *
 * `permission_id` is not merely unwanted, it is unusable: `upsertGrant` in
 * permission.repo.js binds the flags by name and finds the row by
 * `ON CONFLICT (role_id, module_key)` — the natural key, backed by
 * UNIQUE(role_id, module_key). The id is generated by the database and never
 * appears in the DO UPDATE SET list. Nothing is lost by omitting it.
 *
 * Listing the fields rather than destructuring the rest away is deliberate:
 * this is the wire contract, it is short, and a field added to `Grant` should
 * have to be added here consciously — the server's `.strict()` will reject it
 * otherwise, and a reader should be able to see the whole payload without
 * opening another file.
 *
 * 12771 — AND WHY OMITTING A FLAG IS NOT SAFE HERE. The three flags this
 * payload gained (`can_validate`, `can_disburse`, `can_export`) were added to
 * `PERMS`, to `Grant` and to the server's `.strict()` schema, but not to this
 * body. Nothing 4xx'd, because `permission.repo.upsertGrant` now COALESCEs an
 * absent flag against the stored row — an omitted flag means "leave it as it
 * is". So the matrix flipped the checkbox optimistically, sent a body without
 * the flag, got the unchanged row back from `RETURNING *`, wrote it to state,
 * and the checkbox snapped back. Three of the eight columns silently could not
 * be edited. Conscious listing is the point of this block; the list has to
 * actually be kept.
 */
export const upsertGrant = (g: Grant) =>
  tenant<Grant>("/permissions/grant", {
    method: "PUT",
    body: {
      role_id: g.role_id,
      module_key: g.module_key,
      can_create: g.can_create,
      can_read: g.can_read,
      can_update: g.can_update,
      can_delete: g.can_delete,
      can_approve: g.can_approve,
      can_validate: g.can_validate,
      can_disburse: g.can_disburse,
      can_export: g.can_export,
    },
  });
