"use strict";
const service = require("./portal.service");
const clientPortalService = require("./portal_client.service");
const bundles = require("./invoice_bundle.service");
const chat = require("./portal_chat.service");
const notify = require("./portal_notify.service");
const admin = require("./portal_admin.service");
const validator = require("./portal.validator");
const { schemas: portalSchemas } = require("../portal_auth/portal_auth.validator");
const { z } = require("zod");
const { clientPortal } = require("@praxis/shared");

// The staff half's shared forms (14260), with the ids the routes take from
// their paths. One definition of a valid Accept or "Request from client".
const aiReviewRequest = clientPortal.reviewRequest.extend({ client_request_id: z.string().uuid() });
const aiRequestDocuments = clientPortal.documentRequests.extend({ client_id: z.string().uuid() });
// "Send by email" (D8): the key that makes a retry send once is the
// assistant's to pass, or minted for this one call.
const aiMessageEmail = clientPortal.messageEmail.extend({ message_id: z.string().uuid(), request_key: z.string().uuid().optional() });
module.exports = {
  entity: "portal_access", module_key: "MOD-67", screens: [],
  reads: [
    { key: "list_portal_access", service: (c, p) => service.listAccess(c, p), permission: { module: "MOD-67", action: "view" }, describe: "List active portal access grants (client/investor/auditor)." },
    { key: "client_portal_view", service: (c, p) => service.clientView(c, { clientId: p.client_id }), permission: { module: "MOD-29", action: "view" }, describe: "A client's scoped view: their operations files, invoices, receivables ageing." },
    { key: "investor_portal_view", service: (c, p) => service.investorView(c, { params: p }), permission: { module: "MOD-56", action: "view" }, describe: "Investor/board terminal: income statement + cash position." },
    // Client portal redesign (14150): what we are waiting for from clients, and
    // the payments clients say they have made.
    { key: "list_client_requests", service: (c, p) => clientPortalService.staffRequests(c, { clientId: p.client_id || null, status: p.status || null }), permission: { module: "MOD-29", action: "view" }, describe: "Documents and information requested from clients through the portal, with what each client sent back (status OPEN / SUBMITTED / ACCEPTED / REJECTED)." },
    { key: "get_invoice_client_documents", service: (c, p) => bundles.staffView(c, { invoiceId: p.invoice_id }), permission: { module: "MOD-51", action: "view" }, describe: "For one final invoice: the supporting documents its file's reconciliation holds (which lines owe a receipt), and which are already shared with the client in their portal." },
    // The Client inbox (PR 3): every client conversation, those waiting for an
    // answer first; `mine` is the clients the caller looks after and the files
    // they own — which is why this read takes the caller.
    { key: "list_client_inbox", service: (c, p, actor) => chat.staffInbox(c, { filter: (p && p.filter) || "all", actor }), permission: { module: "MOD-64C", action: "view" }, describe: "The Client inbox: every client's portal conversations (General and per shipment) with the last message, how many client messages the team has not read, who looks after the client, and whether it is the caller's own (filter: all | waiting | mine)." },
    { key: "list_client_conversations", service: (c, p) => chat.staffThreads(c, { clientId: p.client_id }), permission: { module: "MOD-64C", action: "view" }, describe: "A client's portal conversations — the General thread and one per shipment — with when each last moved and how many of the client's messages the team has not read." },
    { key: "read_client_conversation", service: (c, p) => chat.staffMessages(c, { clientId: p.client_id, thread: p.thread || "general" }), permission: { module: "MOD-64C", action: "view" }, describe: "The latest messages of one client conversation (thread 'general' or a shipment's dossier_id), with photos, files, voice notes, locations and the shipment stage each message is about — and, on each team message, whether each person at the client was emailed it, read it in the portal, or why not (delivery)." },
    { key: "list_payment_proofs", service: (c, p) => clientPortalService.staffProofs(c, { status: p.status || null, clientId: p.client_id || null }), permission: { module: "MOD-52", action: "view" }, describe: "Proofs of payment clients uploaded in the portal, the invoices each covers, and whether finance has confirmed them." },
    // A client's portal, managed from the Client 360 (MOD-29): who at the
    // client can sign in, their onboarding checklist, and the settings every
    // client shares.
    { key: "list_client_portal_people", service: (c, p) => admin.people(c, { clientId: p.client_id }), permission: { module: "MOD-29", action: "view" }, describe: "Who at one client has access to its client portal: each person's email, what they see (access_scope ALL / OPERATIONS / BILLING), whether they are the client's portal admin (they can invite colleagues), and the last day of their access if it ends." },
    { key: "get_client_onboarding", service: (c, p) => service.clientOnboarding(c, { clientId: p.client_id }), permission: { module: "MOD-29", action: "view" }, describe: "A client's onboarding checklist as the client sees it in their portal: each step (step_key, English and French wording), whether it is done and when, and the percentage complete." },
    { key: "get_client_portal_settings", service: async (c) => ({ invite_defaults: await admin.inviteDefaults(c), onboarding_steps: await admin.onboardingTemplate(c) }), permission: { module: "MOD-29", action: "view" }, describe: "Client-portal settings shared by every client: what a newly invited person sees by default and whether a client's first portal user becomes its admin, and the onboarding checklist every client starts from (steps switched off are listed with is_active false)." },
    { key: "list_client_message_recipients", service: (c, p) => notify.recipientsFor(c, { messageId: p.message_id }).then((r) => r.recipients), permission: { module: "MOD-64C", action: "edit" }, describe: "Who at the client can be emailed one team message (email_client_message): the portal users who can see that conversation, whether each has signed in, and whether they switched message emails off." },
    { key: "client_notification_reach", service: (c, p) => notify.staffReach(c, { clientId: p.client_id }), permission: { module: "MOD-64C", action: "view" }, describe: "Who at a client is told about portal activity, and how: each contact's access, how many phones or computers they allowed notifications on, and which topics (MESSAGES, REQUESTS, QUOTES, BILLING, PROPOSALS, SHIPMENTS) reach them by email and by push." },
  ],
  writes: [
    { key: "grant_portal_access", service: (c, p, actor) => service.grantAccess(c, { portal: p.portal, subjectEmail: p.subject_email, clientId: p.client_id, expiresAt: p.expires_at, accessScope: p.access_scope, isClientAdmin: p.is_client_admin, actor }), schema: validator.schemas.grant, permission: { module: "MOD-67", action: "edit" }, confirm: true, describe: "Grant a client/investor/auditor portal access (auditor time-boxed; a client grant can be limited to OPERATIONS or BILLING)." },
    { key: "request_client_document", service: (c, p, actor) => clientPortalService.createRequest(c, { clientId: p.client_id, dossierId: p.dossier_id || null, kind: p.kind, docTypeCode: p.doc_type_code || null, title: p.title || null, note: p.note || null, dueOn: p.due_on || null, actor }), schema: portalSchemas.staffCreateRequest, permission: { module: "MOD-29", action: "edit" }, confirm: true, describe: "Ask a client, in their portal, for a document (by document type) or a piece of information, optionally for one shipment and by a due date." },
    { key: "review_client_request", service: (c, p, actor) => clientPortalService.reviewRequest(c, { requestId: p.client_request_id, decision: p.decision, note: p.note || null, document: p.document || null, actor }), schema: aiReviewRequest, permission: { module: "MOD-29", action: "edit" }, confirm: true, describe: "Accept or reject (with the reason the client reads) what a client sent for a request, or cancel the request. Accepting a client-level KYC document files it on the Client 360 as VERIFIED under its document type and re-runs compliance; when the type requires them, pass document.expires_on (YYYY-MM-DD) and/or document.issuing_authority (list_client_requests shows accept_fields per request)." },
    { key: "request_client_documents", service: (c, p, actor) => clientPortalService.requestDocuments(c, { clientId: p.client_id, items: p.items, note: p.note || null, dueOn: p.due_on || null, actor }), schema: aiRequestDocuments, permission: { module: "MOD-29", action: "edit" }, confirm: true, describe: "Ask a client, in their portal, for one or more KYC documents by client document type (items: [{document_type_id}] from the client document types, or [{other: 'description'}] for one with no type). One request per type; a type already requested is refused. The client is told by email and push." },
    { key: "confirm_payment_proof", service: (c, p, actor) => clientPortalService.confirmProof(c, { proofId: p.payment_proof_id, treasuryAccountId: p.treasury_account_id || null, actor }), schema: validator.schemas.aiConfirmProof, permission: { module: "MOD-52", action: "create" }, confirm: true, describe: "Confirm a client's proof of payment; when it names invoices a DRAFT receipt is created for finance to post." },
    { key: "publish_invoice_documents", service: (c, p, actor) => bundles.publish(c, { invoiceId: p.invoice_id, docIds: p.doc_ids, actor }), schema: validator.schemas.aiPublishBundle, permission: { module: "MOD-51", action: "edit" }, confirm: true, describe: "Share an issued final invoice with the client's portal together with the chosen supporting documents from its file (the client can download them all as one ZIP)." },
    { key: "withdraw_invoice_documents", service: (c, p, actor) => bundles.withdraw(c, { invoiceId: p.invoice_id, actor }), schema: validator.schemas.aiWithdrawBundle, permission: { module: "MOD-51", action: "edit" }, confirm: true, describe: "Stop sharing a final invoice's supporting documents with the client; the documents stay on the file." },
    { key: "email_client_message", service: (c, p, actor) => notify.emailTeamMessage(c, { messageId: p.message_id, recipients: p.recipients, requestKey: p.request_key || require("crypto").randomUUID(), actor }), schema: aiMessageEmail, permission: { module: "MOD-64C", action: "edit" }, confirm: true, describe: "Email one TEAM message from a client conversation to the client's portal users now, as a branded email with the sender's signature and its files attached (read_client_conversation gives message ids; list_client_message_recipients who can receive it). Never from TEST." },
    { key: "reply_to_client", service: (c, p, actor) => chat.staffSend(c, { clientId: p.client_id, thread: p.thread || "general", body: p.body, actor }), schema: validator.schemas.aiChatReply, permission: { module: "MOD-64C", action: "edit" }, confirm: true, describe: "Reply to a client in their portal chat — in the General thread or a shipment's thread (thread = its dossier_id). The client sees it in the portal and is notified." },
    { key: "change_client_portal_access", service: (c, p, actor) => admin.updatePerson(c, { clientId: p.client_id, grantId: p.portal_access_id, accessScope: p.access_scope, isClientAdmin: p.is_client_admin, expiresAt: p.expires_at, actor }), schema: validator.schemas.aiClientPersonUpdate, permission: { module: "MOD-29", action: "edit" }, confirm: true, describe: "Change what one person at a client sees in the client portal (access_scope ALL / OPERATIONS / BILLING), whether they are the client's portal admin, or the last day of their access (expires_at YYYY-MM-DD; null for no end)." },
    { key: "remove_client_portal_access", service: (c, p, actor) => admin.revokePerson(c, { clientId: p.client_id, grantId: p.portal_access_id, actor }), schema: validator.schemas.aiClientPersonRevoke, permission: { module: "MOD-29", action: "edit" }, confirm: true, describe: "Remove one person's access to a client's portal. They can no longer see that client's shipments, documents or invoices." },
    { key: "toggle_client_onboarding_step", service: (c, p, actor) => service.toggleOnboardingStep(c, { clientId: p.client_id, stepKey: p.step_key, actor }), schema: validator.schemas.aiOnboardingToggle, permission: { module: "MOD-29", action: "edit" }, confirm: true, describe: "Tick one step of a client's onboarding checklist as done — or untick it if it was done. The client sees the change in their portal." },
    { key: "set_client_invite_defaults", service: (c, p, actor) => admin.saveInviteDefaults(c, { accessScope: p.access_scope, firstIsAdmin: p.first_is_admin, actor }), schema: validator.schemas.aiInviteDefaults, permission: { module: "MOD-29", action: "edit" }, confirm: true, describe: "Set, for every client, what a newly invited portal user sees by default (access_scope ALL / OPERATIONS / BILLING) and whether a client's first portal user automatically becomes its admin." },
    { key: "reject_payment_proof", service: (c, p, actor) => clientPortalService.rejectProof(c, { proofId: p.payment_proof_id, note: p.note, actor }), schema: validator.schemas.aiRejectProof, permission: { module: "MOD-52", action: "edit" }, confirm: true, describe: "Reject a client's proof of payment, with the reason the client will read." },
  ],
};
