"use strict";
const service = require("./portal.service");
const clientPortal = require("./portal_client.service");
const bundles = require("./invoice_bundle.service");
const chat = require("./portal_chat.service");
const validator = require("./portal.validator");
const { schemas: portalSchemas } = require("../portal_auth/portal_auth.validator");
module.exports = {
  entity: "portal_access", module_key: "MOD-67", screens: [],
  reads: [
    { key: "list_portal_access", service: (c, p) => service.listAccess(c, p), permission: { module: "MOD-67", action: "view" }, describe: "List active portal access grants (client/investor/auditor)." },
    { key: "client_portal_view", service: (c, p) => service.clientView(c, { clientId: p.client_id }), permission: { module: "MOD-29", action: "view" }, describe: "A client's scoped view: their operations files, invoices, receivables ageing." },
    { key: "investor_portal_view", service: (c, p) => service.investorView(c, { params: p }), permission: { module: "MOD-56", action: "view" }, describe: "Investor/board terminal: income statement + cash position." },
    // Client portal redesign (14150): what we are waiting for from clients, and
    // the payments clients say they have made.
    { key: "list_client_requests", service: (c, p) => clientPortal.staffRequests(c, { clientId: p.client_id || null, status: p.status || null }), permission: { module: "MOD-29", action: "view" }, describe: "Documents and information requested from clients through the portal, with what each client sent back (status OPEN / SUBMITTED / ACCEPTED / REJECTED)." },
    { key: "get_invoice_client_documents", service: (c, p) => bundles.staffView(c, { invoiceId: p.invoice_id }), permission: { module: "MOD-51", action: "view" }, describe: "For one final invoice: the supporting documents its file's reconciliation holds (which lines owe a receipt), and which are already shared with the client in their portal." },
    { key: "list_client_conversations", service: (c, p) => chat.staffThreads(c, { clientId: p.client_id }), permission: { module: "MOD-67", action: "view" }, describe: "A client's portal conversations — the General thread and one per shipment — with when each last moved and how many of the client's messages the team has not read." },
    { key: "read_client_conversation", service: (c, p) => chat.staffMessages(c, { clientId: p.client_id, thread: p.thread || "general" }), permission: { module: "MOD-67", action: "view" }, describe: "The latest messages of one client conversation (thread 'general' or a shipment's dossier_id), with photos, files, voice notes, locations and the shipment stage each message is about." },
    { key: "list_payment_proofs", service: (c, p) => clientPortal.staffProofs(c, { status: p.status || null, clientId: p.client_id || null }), permission: { module: "MOD-52", action: "view" }, describe: "Proofs of payment clients uploaded in the portal, the invoices each covers, and whether finance has confirmed them." },
  ],
  writes: [
    { key: "grant_portal_access", service: (c, p, actor) => service.grantAccess(c, { portal: p.portal, subjectEmail: p.subject_email, clientId: p.client_id, expiresAt: p.expires_at, accessScope: p.access_scope, isClientAdmin: p.is_client_admin, actor }), schema: validator.schemas.grant, permission: { module: "MOD-67", action: "edit" }, confirm: true, describe: "Grant a client/investor/auditor portal access (auditor time-boxed; a client grant can be limited to OPERATIONS or BILLING)." },
    { key: "request_client_document", service: (c, p, actor) => clientPortal.createRequest(c, { clientId: p.client_id, dossierId: p.dossier_id || null, kind: p.kind, docTypeCode: p.doc_type_code || null, title: p.title || null, note: p.note || null, dueOn: p.due_on || null, actor }), schema: portalSchemas.staffCreateRequest, permission: { module: "MOD-29", action: "edit" }, confirm: true, describe: "Ask a client, in their portal, for a document (by document type) or a piece of information, optionally for one shipment and by a due date." },
    { key: "review_client_request", service: (c, p, actor) => clientPortal.reviewRequest(c, { requestId: p.client_request_id, decision: p.decision, note: p.note || null, actor }), schema: validator.schemas.aiReviewRequest, permission: { module: "MOD-29", action: "edit" }, confirm: true, describe: "Accept or reject (with the reason the client reads) what a client sent for a request, or cancel the request." },
    { key: "confirm_payment_proof", service: (c, p, actor) => clientPortal.confirmProof(c, { proofId: p.payment_proof_id, treasuryAccountId: p.treasury_account_id || null, actor }), schema: validator.schemas.aiConfirmProof, permission: { module: "MOD-52", action: "create" }, confirm: true, describe: "Confirm a client's proof of payment; when it names invoices a DRAFT receipt is created for finance to post." },
    { key: "publish_invoice_documents", service: (c, p, actor) => bundles.publish(c, { invoiceId: p.invoice_id, docIds: p.doc_ids, actor }), schema: validator.schemas.aiPublishBundle, permission: { module: "MOD-51", action: "edit" }, confirm: true, describe: "Share an issued final invoice with the client's portal together with the chosen supporting documents from its file (the client can download them all as one ZIP)." },
    { key: "withdraw_invoice_documents", service: (c, p, actor) => bundles.withdraw(c, { invoiceId: p.invoice_id, actor }), schema: validator.schemas.aiWithdrawBundle, permission: { module: "MOD-51", action: "edit" }, confirm: true, describe: "Stop sharing a final invoice's supporting documents with the client; the documents stay on the file." },
    { key: "reply_to_client", service: (c, p, actor) => chat.staffSend(c, { clientId: p.client_id, thread: p.thread || "general", body: p.body, actor }), schema: validator.schemas.aiChatReply, permission: { module: "MOD-67", action: "edit" }, confirm: true, describe: "Reply to a client in their portal chat — in the General thread or a shipment's thread (thread = its dossier_id). The client sees it in the portal and is notified." },
    { key: "reject_payment_proof", service: (c, p, actor) => clientPortal.rejectProof(c, { proofId: p.payment_proof_id, note: p.note, actor }), schema: validator.schemas.aiRejectProof, permission: { module: "MOD-52", action: "edit" }, confirm: true, describe: "Reject a client's proof of payment, with the reason the client will read." },
  ],
};
