"use strict";
const service = require("./quote_request.service");
const validator = require("./quote_request.validator");
module.exports = {
  entity: "quote_request",
  module_key: "MOD-20",
  screens: [],
  reads: [
    { key: "list_quote_requests", service: (c, p) => service.list(c, p).then((r) => ({ rows: r.rows, total: r.total, kpi: r.kpi })), permission: { module: "MOD-20", action: "view" }, describe: "List intake quote requests. Filters: status, intake_channel (MANUAL, WEBSITE, PORTAL, EMAIL, REFERRAL, CAMPAIGN), service_type_id, client_id, open (true = neither converted nor closed), q. Each row carries the service's names and card (service_name_en / service_name_fr / service_mode) and the client's name. Returns rows + total + the KPI tiles, one per intake status plus TOTAL, which partition the filtered set." },
    { key: "get_quote_request", service: (c, p) => service.get(c, p.id || p), permission: { module: "MOD-20", action: "view" }, describe: "Get a quote request by id, with attachments." },
    { key: "list_quote_request_services", service: (c) => service.quoteServices(c), permission: { module: "MOD-20", action: "view" }, describe: "The service types a quote request can name: each with its id, English and French name, card (SEA / AIR / RAIL / ROAD / STORAGE / CUSTOMS / OTHER), flow (IMPORT / EXPORT / END_TO_END / INLAND / HINTERLAND, or null), enquiry shape (ROUTE / STORAGE / NONE) and the Incoterms it offers. Use it to pick the service_type_id for create_quote_request." },
    { key: "suggest_quote_request_client", service: (c, p) => service.clientMatch(c, { email: p.email }), permission: { module: "MOD-20", action: "view" }, describe: "Which client a requester's email address belongs to: an exact match on a client contact or the client record first, then the company domain (never a public webmail domain such as gmail.com). Returns one suggestion when exactly one client answers, plus the candidates weighed." },
  ],
  writes: [
    { key: "create_quote_request", service: (c, p, actor) => service.create(c, { data: p, actor }), schema: validator.schemas.create, permission: { module: "MOD-20", action: "create" }, confirm: true, describe: "Create a new quote request. `incoterm` is required and must be one the service offers (or TBD for 'to be determined'). Name the service by `service_type_id` (see list_quote_request_services) — `service_category` is then written from its name; for a hinterland transit say `hinterland_direction` INTO or OUT_OF. Give `client_id` when the request is for an existing client: it then appears in their portal and their account manager becomes its owner. Public reference is allocated from the tenant's numbering scheme in the same transaction." },
    { key: "link_quote_request_client", service: (c, p, actor) => service.update(c, { id: p.quote_request_id, patch: { client_id: p.client_id }, actor }), schema: validator.schemas.aiLinkClient, permission: { module: "MOD-20", action: "edit" }, confirm: true, describe: "Tie a quote request to an existing client (by client_id). The request then appears in that client's portal, and the client's account manager becomes its owner if it has none. Refused once the request is converted or closed." },
    { key: "file_chat_document_on_quote_request", service: (c, p, actor) => service.fileFromChat(c, { id: p.quote_request_id, chatAttachmentId: p.chat_attachment_id, documentKind: p.document_kind || null, actor }), schema: validator.schemas.aiFileFromChat, permission: { module: "MOD-20", action: "edit" }, confirm: true, describe: "File a document the client sent in their portal chat (chat_attachment_id, from read_client_conversation) on one of that client's open quote requests — the same file is linked, not copied. document_kind: COMMERCIAL_INVOICE, PROFORMA, PACKING_LIST, BL_AWB, CARGO_PHOTOS or OTHER." },
    { key: "transition_quote_request", service: (c, p, actor) => service.transition(c, { id: p.quote_request_id, to: p.to, actor }), schema: validator.schemas.aiTransition, permission: { module: "MOD-20", action: "edit" }, confirm: true, describe: "Advance a quote request by id through the intake lifecycle (RECEIVED -> UNDER_REVIEW -> QUOTED -> CONVERTED_TO_OPPORTUNITY). Moving an unowned request to UNDER_REVIEW makes the caller its owner." },
    { key: "convert_quote_request", service: (c, p, actor) => service.convertToOpportunity(c, { id: p.quote_request_id, opportunity: p.opportunity, actor }), schema: validator.schemas.aiConvert, permission: { module: "MOD-20", action: "approve" }, confirm: true, describe: "Convert a quote request into an opportunity in the pipeline. The opportunity starts in NEW; staff move it from there." },
  ],
};
