-- ============================================================================
-- SEED (per tenant schema) — OHADA / SYSCOHADA chart of accounts
-- A high-frequency working subset for a Cameroon freight forwarder (KB Appendix A,
-- ★ accounts). Insert order respects parent_code FK: 2-digit -> 3-digit -> 4-digit.
-- Seed the FULL 4-digit plan from the annexed AUDCIF at go-live; this is the spine.
-- is_postable = true only on leaf accounts actually posted to.
-- ============================================================================

-- Helper note: normal_balance D=debit C=credit; requires_analytic on 4731/706/707.

-- 2-DIGIT HEADINGS (parent_code NULL) ---------------------------------------
INSERT INTO chart_of_accounts (code,parent_code,label_fr,label_en,class,normal_balance,is_postable,requires_analytic) VALUES
 ('13',NULL,'Résultat net de l''exercice','Net result',1,'C',false,false),
 ('16',NULL,'Emprunts et dettes assimilées','Loans & similar debt',1,'C',false,false),
 ('18',NULL,'Comptes de liaison (inter-entités)','Inter-entity liaison',1,'C',false,false),
 ('21',NULL,'Immobilisations incorporelles','Intangible assets',2,'D',false,false),
 ('23',NULL,'Bâtiments, installations, agencements','Buildings & fittings',2,'D',false,false),
 ('24',NULL,'Matériel, mobilier','Equipment & furniture',2,'D',false,false),
 ('28',NULL,'Amortissements','Accumulated depreciation',2,'C',false,false),
 ('33',NULL,'Autres approvisionnements','Other supplies',3,'D',false,false),
 ('40',NULL,'Fournisseurs et comptes rattachés','Suppliers',4,'C',false,false),
 ('41',NULL,'Clients et comptes rattachés','Customers',4,'D',false,false),
 ('42',NULL,'Personnel','Personnel',4,'C',false,false),
 ('43',NULL,'Organismes sociaux','Social bodies',4,'C',false,false),
 ('44',NULL,'État et collectivités publiques','State & public authorities',4,'C',false,false),
 ('47',NULL,'Débiteurs et créditeurs divers','Sundry debtors/creditors',4,'D',false,false),
 ('48',NULL,'Créances et dettes HAO','Non-operating receivables/payables',4,'C',false,false),
 ('52',NULL,'Banques','Banks',5,'D',false,false),
 ('53',NULL,'Établissements financiers','Financial establishments',5,'D',false,false),
 ('57',NULL,'Caisse','Cash on hand',5,'D',false,false),
 ('58',NULL,'Régies d''avances et virements internes','Imprest & internal transfers',5,'D',false,false),
 ('60',NULL,'Achats','Purchases',6,'D',false,false),
 ('61',NULL,'Transports','Transport',6,'D',false,false),
 ('62',NULL,'Services extérieurs A','External services A',6,'D',false,false),
 ('63',NULL,'Services extérieurs B','External services B',6,'D',false,false),
 ('64',NULL,'Impôts et taxes','Taxes (non-income)',6,'D',false,false),
 ('66',NULL,'Charges de personnel','Personnel expenses',6,'D',false,false),
 ('67',NULL,'Frais financiers','Financial expenses',6,'D',false,false),
 ('68',NULL,'Dotations aux amortissements','Depreciation expense',6,'D',false,false),
 ('70',NULL,'Ventes','Sales / revenue',7,'C',false,false),
 ('75',NULL,'Autres produits','Other operating income',7,'C',false,false),
 ('77',NULL,'Revenus financiers','Financial income',7,'C',false,false),
 ('81',NULL,'Valeurs comptables des cessions','NBV of disposed assets',8,'D',false,false),
 ('82',NULL,'Produits des cessions d''immobilisations','Proceeds from disposals',8,'C',false,false),
 ('89',NULL,'Impôts sur le résultat','Income taxes',8,'D',false,false);

-- 3-DIGIT ACCOUNTS ----------------------------------------------------------
INSERT INTO chart_of_accounts (code,parent_code,label_fr,label_en,class,normal_balance,is_postable,requires_analytic) VALUES
 ('131','13','Résultat net : bénéfice','Net profit',1,'C',true,false),
 ('162','16','Emprunts auprès des établissements de crédit','Bank loans',1,'C',true,false),
 ('213','21','Logiciels et sites internet','Software & websites',2,'D',true,false),
 ('231','23','Bâtiments sur sol propre','Buildings on own land',2,'D',true,false),
 ('245','24','Matériel de transport','Transport equipment (fleet)',2,'D',true,false),
 ('284','28','Amortissements du matériel','Depreciation of equipment',2,'C',false,false),
 ('331','33','Matières consommables','Consumables',3,'D',true,false),
 ('401','40','Fournisseurs, dettes en compte','Trade payables',4,'C',false,false),
 ('409','40','Fournisseurs débiteurs','Supplier debit balances',4,'D',false,false),
 ('411','41','Clients','Trade receivables',4,'D',false,false),
 ('418','41','Clients, produits à recevoir','Accrued client income',4,'D',false,false),
 ('419','41','Clients créditeurs','Customer credit balances',4,'C',false,false),
 ('421','42','Personnel, avances et acomptes','Staff advances',4,'D',false,false),
 ('422','42','Personnel, rémunérations dues','Net pay payable',4,'C',true,false),
 ('431','43','Sécurité sociale (CNPS)','Social security (CNPS)',4,'C',true,false),
 ('441','44','État, impôt sur les bénéfices','Corporate income tax',4,'C',true,false),
 ('443','44','État, TVA facturée','Output VAT',4,'C',false,false),
 ('444','44','État, TVA due ou crédit','Net VAT position',4,'C',false,false),
 ('445','44','État, TVA récupérable','Input (recoverable) VAT',4,'D',false,false),
 ('447','44','État, impôts retenus à la source','Taxes withheld at source',4,'C',false,false),
 ('449','44','État, créances et dettes diverses','Other State receivables/payables',4,'D',false,false),
 ('473','47','Intermédiaires, opérations pour compte de tiers','Agent — third-party operations',4,'D',false,true),
 ('476','47','Charges constatées d''avance','Prepaid expenses',4,'D',true,false),
 ('477','47','Produits constatés d''avance','Deferred income',4,'C',true,false),
 ('478','47','Écarts de conversion – Actif','FX translation asset',4,'D',true,false),
 ('479','47','Écarts de conversion – Passif','FX translation liability',4,'C',true,false),
 ('481','48','Fournisseurs d''investissements','Fixed-asset suppliers',4,'C',true,false),
 ('485','48','Créances sur cessions d''immobilisations','Receivable on disposals',4,'D',true,false),
 ('521','52','Banques locales','Local banks',5,'D',false,false),
 ('538','53','Autres organismes financiers (Mobile Money)','Other financial orgs (MoMo)',5,'D',false,false),
 ('571','57','Caisse siège','Head-office cash',5,'D',true,false),
 ('581','58','Régies d''avances','Imprest advances',5,'D',true,false),
 ('585','58','Virements de fonds','Internal fund transfers',5,'D',true,false),
 ('605','60','Autres achats','Other purchases',6,'D',false,false),
 ('613','61','Transports pour le compte de tiers','Transport for third parties',6,'D',true,true),
 ('621','62','Sous-traitance générale','General subcontracting',6,'D',true,true),
 ('624','62','Entretien, réparations, maintenance','Maintenance & repairs',6,'D',true,false),
 ('625','62','Primes d''assurance','Insurance premiums',6,'D',true,false),
 ('631','63','Frais bancaires','Bank charges',6,'D',true,false),
 ('632','63','Rémunérations d''intermédiaires et conseils','Intermediary & advisory fees',6,'D',true,false),
 ('641','64','Impôts et taxes directs','Direct taxes',6,'D',true,false),
 ('661','66','Rémunérations directes personnel national','Direct national staff pay',6,'D',true,false),
 ('664','66','Charges sociales','Employer social charges',6,'D',true,false),
 ('676','67','Pertes de change','Realised FX loss',6,'D',true,false),
 ('681','68','Dotations amortissements d''exploitation','Operating depreciation',6,'D',false,false),
 ('706','70','Services vendus','Services sold',7,'C',false,true),
 ('707','70','Produits accessoires','Ancillary income',7,'C',true,true),
 ('758','75','Produits divers','Sundry income',7,'C',true,false),
 ('776','77','Gains de change','Realised FX gain',7,'C',true,false),
 ('812','81','Valeurs comptables cessions corporelles','NBV of disposed tangibles',8,'D',true,false),
 ('822','82','Produits des cessions corporelles','Proceeds from tangible disposals',8,'C',true,false),
 ('891','89','Impôts sur les bénéfices de l''exercice','Corporate income tax charge',8,'D',true,false);

-- 4-DIGIT LEAVES actually posted to (is_postable=true) -----------------------
INSERT INTO chart_of_accounts (code,parent_code,label_fr,label_en,class,normal_balance,is_postable,requires_analytic) VALUES
 ('2845','284','Amortissements du matériel de transport','Depr. of transport equipment',2,'C',true,false),
 ('4011','401','Fournisseurs','Trade suppliers',4,'C',true,false),
 ('4013','401','Fournisseurs sous-traitants','Subcontractor suppliers',4,'C',true,false),
 ('4091','409','Fournisseurs, avances versées','Advances to suppliers',4,'D',true,false),
 ('4111','411','Clients','Customers',4,'D',true,false),
 ('4181','418','Clients, factures à établir','Accrued client billing',4,'D',true,true),
 ('4191','419','Clients, avances et acomptes reçus','Customer advances received',4,'C',true,false),
 ('4211','421','Personnel, avances','Staff advances',4,'D',true,false),
 ('4312','431','CNPS accidents du travail','CNPS work injury',4,'C',true,false),
 ('4313','431','CNPS caisse de retraite','CNPS pension',4,'C',true,false),
 ('4431','443','TVA facturée sur ventes','Output VAT on sales',4,'C',true,false),
 ('4432','443','TVA facturée sur prestations de services','Output VAT on services',4,'C',true,false),
 ('4441','444','TVA due','VAT payable',4,'C',true,false),
 ('4449','444','Crédit de TVA à reporter','VAT credit carry-forward',4,'D',true,false),
 ('4451','445','TVA récupérable sur immobilisations','Input VAT on assets',4,'D',true,false),
 ('4452','445','TVA récupérable sur achats','Input VAT on purchases',4,'D',true,false),
 ('4453','445','TVA récupérable sur transport','Input VAT on transport',4,'D',true,false),
 ('4454','445','TVA récupérable sur services extérieurs','Input VAT on external services',4,'D',true,false),
 ('4471','447','Impôt sur traitements et salaires (IRPP+CAC)','Payroll withholding (IRPP+CAC)',4,'C',true,false),
 ('4474','447','Autres retenues (WHT fournisseurs)','Other withholding (supplier WHT)',4,'C',true,false),
 ('4492','449','Acomptes/avances sur impôts (précompte subi)','Tax instalments / WHT suffered',4,'D',true,false),
 ('4731','473','Mandants','Principals (débours account)',4,'D',true,true),
 ('5211','521','Banque principale','Main bank account',5,'D',true,false),
 ('5381','538','MTN Mobile Money','MTN MoMo',5,'D',true,false),
 ('5382','538','Orange Money','Orange Money',5,'D',true,false),
 ('6053','605','Carburants','Fuel',6,'D',true,true),
 ('6813','681','Dotations amort. immobilisations corporelles','Depr. of tangible assets',6,'D',true,false),
 ('7061','706','Transport / fret','Transport / freight',7,'C',true,true),
 ('7062','706','Commission de transit','Transit commission',7,'C',true,true),
 ('7063','706','Frais de documentation','Documentation fees',7,'C',true,true),
 ('7064','706','Manutention','Handling (own name)',7,'C',true,true);
