/**
 * On-demand AI explanation of an error (spec §7).
 *
 * Deliberately reuses `services/ai/llm.service.chat()` rather than calling a
 * provider directly: that module already implements the DeepSeek-primary /
 * Gemini-fallback chain §7.4 asks for, sourcing keys from the encrypted
 * platform.ai_vendor_credential store. A second HTTP client here would mean two
 * places to rotate a key and two places to get the fallback wrong.
 *
 * THREE CACHE TIERS, keyed on signature and not error_id
 *
 *   The same fault in two tenants is the same explanation. Keying on error_id
 *   would pay the model once per tenant for one answer.
 *
 *   1. Redis, 1h TTL (§7.5) — absorbs the "everyone clicks Explain during an
 *      incident" burst.
 *   2. platform.error_explanation — durable, survives a cache flush and a
 *      deploy, and is what the detail drawer renders on first paint without
 *      spending a token.
 *   3. `force` bypasses both, for the mockup's [Regenerate] button.
 *
 * WHAT IS SENT TO THE MODEL
 *
 *   Message, parsed frames, module, route, counts, plus the codebase brief and
 *   the candidate directory for the route (see `services/ai/codebase-brief.js`).
 *   NOT `context` — that carries request_id, user_id and browser URL, and §11
 *   requires error data be sanitised of PII before it leaves. The stack is
 *   truncated to the frames that identify the fault; a 40-frame trace does not
 *   explain better than 12.
 *
 * WHY THE PROMPT IS NO LONGER THE SPEC'S OWN WORDING
 *
 *   §7.4's prompt opens "specializing in Node.js/NestJS debugging", because the
 *   spec was written against an assumed stack — the same assumption
 *   `doc/TESTING_ErrorMonitor_Module.md` §0 already records for the routes, the
 *   tables and the exception filters. Left in, it was the most load-bearing
 *   sentence in the prompt: a 422 from POST /api/tenant/mail/send came back
 *   explained in terms of a `SendMailDto`, a `MailModule`, class-validator
 *   decorators and a NestJS ValidationPipe, none of which exist here. The four
 *   sections §7.1 requires are unchanged and still pinned by a test; what
 *   changed is the stack the model is told it is looking at, which is now
 *   stated as fact and checked against the tree.
 */

"use strict";

const { logger } = require("../../config/logger");
const db = require("./db");
const { AppError } = require("../../utils/errors");
const llm = require("../ai/llm.service");
const { CODEBASE_BRIEF, whereToLook } = require("../ai/codebase-brief");

const CACHE_TTL_SECONDS = 3600;
const CACHE_PREFIX = "err:explain:";
/**
 * Bumped when the prompt changes, and READ BACK on the way out of both caches.
 *
 * It was written into `platform.error_explanation` and never looked at again,
 * so an explanation generated by an older prompt was served forever — a fix to
 * the prompt would have reached only signatures nobody had explained yet, which
 * is precisely the signatures nobody is looking at. v2 is the codebase brief.
 */
const PROMPT_VERSION = 2;
const MAX_FRAMES = 12;

/**
 * Spec §7.4's four sections, verbatim — the contract the format is tested
 * against — over the facts of the codebase they are being asked about.
 *
 * The closing rules are the anti-invention half, and they are as important as
 * the brief: a model given a stack trace it cannot place will reach for the
 * shape it has seen most often unless told what to do instead.
 */
const SYSTEM_PROMPT = `You are an expert backend developer debugging Praxis LS, the system described below.
Explain this error in plain English for a non-technical ops team lead. Include:
1. What happened (one sentence)
2. Why it happened (technical cause)
3. Which module/function is responsible
4. Suggested fix (code snippet if applicable)

Format your response in clear sections. Keep explanations concise but actionable.

${CODEBASE_BRIEF}

RULES
- Name only files, functions and symbols that appear in the report above or
  follow from the layout described here. Never invent a class, decorator,
  service or file name; a plausible-sounding path nobody can open is worse than
  saying you do not know which file it is.
- Any code you suggest must fit this codebase: CommonJS, Express, Zod, plain
  SQL. Do not write NestJS, DTO classes, decorators or ORM calls.
- If the report does not identify the responsible code, say so plainly and name
  the files worth opening first, rather than filling the gap with a guess.
- The reader is an ops lead, not the author: say what the effect on a user was
  before saying what the code did.`;

function redis() {
  try {
     
    return require("../../config/redis").getClient();
  } catch {
    // Redis absent (tests, a worker without it): fall through to the DB tier.
    return null;
  }
}

/** The prompt version is IN the key: a new prompt must not read old answers. */
const cacheKey = (signature) => `${CACHE_PREFIX}v${PROMPT_VERSION}:${signature}`;

async function fromRedis(signature) {
  const c = redis();
  if (!c) return null;
  try {
    const hit = await c.get(cacheKey(signature));
    return hit ? JSON.parse(hit) : null;
  } catch {
    return null;
  }
}

async function toRedis(signature, value) {
  const c = redis();
  if (!c) return;
  try {
    await c.set(cacheKey(signature), JSON.stringify(value), "EX", CACHE_TTL_SECONDS);
  } catch {
    /* @silent:storage caching is best-effort — Redis being unreachable must not
       deny an explanation that has already been generated and paid for. */
  }
}

/** Build the user-turn context payload described in §7.3. */
function buildContext(row) {
  const frames = Array.isArray(row.stack_trace) ? row.stack_trace.slice(0, MAX_FRAMES) : [];
  const chain = frames
    .map((f) => `  [${f.index}] ${f.file || "?"}:${f.line || "?"} → ${f.function || "?"}`)
    .join("\n");

  // Which directory serves this route, read from the module tree at runtime.
  // The one fact the report itself never carries: a synthetic ValidationError's
  // only frame is the route, and `module`/`file_path` come back empty.
  const where = whereToLook(row.route);

  return [
    `Error: ${row.name || "Error"}: ${row.message}`,
    `Level: ${row.level}`,
    `Origin: ${row.origin}`,
    row.module ? `Module: ${row.module}` : null,
    row.route ? `Route: ${row.route}` : null,
    row.file_path ? `Location: ${row.file_path}:${row.line_number || "?"}` : null,
    `Occurrences: ${row.occurrence_count}`,
    `First seen: ${row.first_seen}`,
    `Last seen: ${row.last_seen}`,
    chain ? `\nStack trace:\n${chain}` : null,
    where ? `\n${where}` : null,
  ]
    .filter(Boolean)
    .join("\n");
}

/**
 * @param {object} opts
 * @param {string} opts.errorId
 * @param {string} [opts.actorId] platform user requesting it
 * @param {boolean} [opts.force] bypass both caches (Regenerate)
 */
async function explain({ errorId, actorId = null, force = false }) {
  const { rows } = await db.query(
    `SELECT error_id, signature, level, origin, name, message, module, route,
            file_path, line_number, occurrence_count, first_seen, last_seen, stack_trace
       FROM platform.error_event WHERE error_id = $1`,
    [errorId],
  );
  const row = rows[0];
  if (!row) throw new AppError("NOT_FOUND", "Error not found", 404);

  if (!force) {
    const cached = await fromRedis(row.signature);
    if (cached) return { ...cached, cached: true, source: "redis" };

    // AND prompt_version: a row written by an earlier prompt is not an answer
    // to the current one. It is left in place and overwritten on regeneration,
    // so the history of what was said is not silently deleted either.
    const stored = await db.query(
      `SELECT explanation, generated_by, model, created_at
         FROM platform.error_explanation
        WHERE signature = $1 AND prompt_version = $2`,
      [row.signature, PROMPT_VERSION],
    );
    if (stored.rows[0]) {
      const value = {
        signature: row.signature,
        explanation: stored.rows[0].explanation,
        generated_by: stored.rows[0].generated_by,
        model: stored.rows[0].model,
        generated_at: stored.rows[0].created_at,
      };
      await toRedis(row.signature, value);
      return { ...value, cached: true, source: "db" };
    }
  }

  const result = await llm.chat({
    client: null,
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      { role: "user", content: buildContext(row) },
    ],
    temperature: 0.2,
  });

  // llm.chat returns a STUB with provider:null when no vendor is configured.
  // Storing that would poison the cache with an apology, and every later call
  // would serve it back as a real explanation.
  if (!result.provider) {
    throw new AppError(
      "AI_UNAVAILABLE",
      "No AI provider is configured. Add DeepSeek or Gemini credentials under Integrations → AI providers.",
      503,
    );
  }

  const value = {
    signature: row.signature,
    explanation: result.text,
    generated_by: result.provider,
    model: null,
    generated_at: new Date().toISOString(),
  };

  try {
    await db.query(
      `INSERT INTO platform.error_explanation
         (signature, explanation, generated_by, model, prompt_version, requested_by)
       VALUES ($1, $2, $3, $4, $5, $6)
       ON CONFLICT (signature) DO UPDATE
         SET explanation = EXCLUDED.explanation,
             generated_by = EXCLUDED.generated_by,
             prompt_version = EXCLUDED.prompt_version,
             requested_by = EXCLUDED.requested_by,
             updated_at = now()`,
      [row.signature, value.explanation, value.generated_by, value.model, PROMPT_VERSION, actorId],
    );
  } catch (err) {
    // The explanation is already generated and useful; failing to file it away
    // should not deny it to the person who asked.
    logger.warn({ err, signature: row.signature }, "failed to persist error explanation");
  }

  await toRedis(row.signature, value);
  return { ...value, cached: false, source: "live" };
}

module.exports = { explain, buildContext, SYSTEM_PROMPT, CACHE_TTL_SECONDS, PROMPT_VERSION };
