/**
 * The client portal's copy — EN and FR — out of the entry dictionary.
 *
 * Every string a signed-in client, investor or auditor reads in the portal is
 * here, and only the portal's chunk downloads it: `i18n-dict.ts` is in the
 * entry graph, and a visitor reading the home page should not pay for the
 * portal's three hundred strings (`check-bundle.mjs`, first paint at 99 %).
 * Registered at runtime by `portal-i18n.ts`, mounted at `portal.*`.
 *
 * ── THE PORTAL'S VOICE ────────────────────────────────────────────────────
 *
 * Short. The owner's brief for the redesign was "less text": a label is a
 * word or two, a status is a pill, and an explanation is behind an ⓘ rather
 * than printed on the screen. Counts are written as "Label: n" rather than as
 * plural sentences, because `check:i18n` reads this file statically and a
 * `key_one` / `key_other` pair is a dangling call to it (see
 * `site.about.networkPlaces` in `i18n-dict.ts`).
 *
 * ── THE RULES THIS FILE KEEPS ─────────────────────────────────────────────
 *
 *   1. NO IMPORTS, NO EXPRESSIONS — two object literals and `as const`, like
 *      `i18n-dict.ts`; `check:i18n` reads it as data.
 *   2. FRENCH TYPOGRAPHY (`doc/BRAND_GLOSSARY_FR_EN.md` §5): a narrow
 *      no-break space (U+202F) before `: ; ! ?`, the typographic apostrophe.
 *      `check:i18n` enforces both here as in the main dictionary.
 *   3. SERVER ERROR CODES under `err` are the codes the API returns; the
 *      portal shows the sentence for the code, never the server's English
 *      message (`ui/kit.tsx`, `errorText`).
 */

export const en = {
  brandFallback: "Client portal",
  offline: "You’re offline. Check your connection and try again.",
  nav: {
    label: "Main",
    home: "Home",
    shipments: "Shipments",
    quotes: "Quotes",
    billing: "Billing",
    documents: "Documents",
    account: "Account",
  },
  common: {
    back: "Back",
    close: "Close",
    notNow: "Not now",
    retry: "Try again",
    loading: "Loading",
    seeAll: "See all",
    cancel: "Cancel",
    save: "Save",
    next: "Next",
    download: "Download",
    pdf: "PDF",
    copy: "Copy",
    copied: "Copied",
    clear: "Clear",
    calendar: "Open calendar",
    datePlaceholder: "dd/mm/yyyy",
  },
  kind: {
    CLIENT: "Client",
    INVESTOR: "Investor",
    AUDITOR: "Auditor",
  },
  mode: {
    SEA: "Sea freight",
    AIR: "Air freight",
    ROAD: "Road",
    RAIL: "Rail",
    STORAGE: "Storage",
    CUSTOMS: "Customs",
    OTHER: "Other",
  },
  signin: {
    title: "Sign in",
    sub: "Your shipments, documents and invoices.",
    eyebrow: "Client portal",
    // One sentence in two halves: the second arrives on its own beat in the
    // tenant's colour, exactly as the homepage headline's does.
    taglineMain: "Everything about your cargo,",
    taglineAccent: "in one place.",
    trackLink: "Track a shipment without signing in",
    themeDark: "Switch to dark mode",
    themeLight: "Switch to light mode",
    whatsInside: "What’s inside",
    feature: {
      track: "Follow every shipment, step by step",
      documents: "Download your documents and invoices",
      send: "Send the documents we need, straight from your phone",
      pay: "See what’s due and send proof of payment",
      chat: "Message the team handling your cargo",
      team: "Invite your colleagues",
    },
    accessNote: "Access is by invitation from your account manager.",
    email: "Email",
    emailPlaceholder: "you@company.com",
    continue: "Continue",
    usePassword: "Use my password",
    emailMeCode: "Email me a code",
    welcomeBackNamed: "Welcome back, {{name}}",
    welcomeBack: "Welcome back",
    notYou: "Not {{email}}?",
    keep: "Keep me signed in",
    keepHint: "On this device, for 30 days",
    checkEmail: "Check your email",
    codeSent: "We sent a 6-digit code to {{email}}",
    codeLabel: "Sign-in code",
    digit: "Digit {{n}}",
    resend: "Send a new code",
    resendIn: "New code in {{s}}s",
    checking: "Checking…",
    passwordTitle: "Enter your password",
    password: "Password",
    signIn: "Sign in",
    forgot: "Forgot password?",
    resetSent: "If this address has access, a link to choose a new password is on its way.",
    back: "Back",
    showPassword: "Show password",
    hidePassword: "Hide password",
    bio: {
      face: "Continue with Face ID",
      touch: "Continue with Touch ID",
      hello: "Continue with Windows Hello",
      finger: "Continue with fingerprint",
    },
  },
  setPassword: {
    title: "Choose your password",
    sub: "You’ll use it with your email to sign in.",
    new: "New password",
    confirm: "Type it again",
    mismatch: "The two passwords don’t match.",
    cta: "Save and sign in",
    badLinkTitle: "This link doesn’t work",
    badLink: "Use the link exactly as it appears in your email, or ask for a new one.",
    rule: {
      length: "12+ characters",
      upper: "A capital letter",
      lower: "A small letter",
      digit: "A number",
      symbol: "A symbol",
    },
  },
  passkey: {
    offerTitle: {
      face: "Use Face ID next time?",
      touch: "Use Touch ID next time?",
      hello: "Use Windows Hello next time?",
      finger: "Use your fingerprint next time?",
    },
    offerBody: "One touch to sign in — no code, no password.",
    turnOn: "Turn on",
    on: {
      face: "Face ID is on",
      touch: "Touch ID is on",
      hello: "Windows Hello is on",
      finger: "Fingerprint sign-in is on",
    },
    off: "Turned off on this device",
    label: {
      face: "Face ID",
      touch: "Touch ID",
      hello: "Windows Hello",
      finger: "Fingerprint",
    },
    thisDevice: "On this device",
  },
  noAccess: {
    title: "No active access",
    hint: "Your access has ended or was switched off. Your account manager can restore it.",
  },
  err: {
    generic: "Something went wrong. Please try again.",
    BAD_CREDENTIALS: "That email and password don’t match.",
    INVALID_CODE: "That code isn’t right, or it has expired.",
    RATE_LIMITED: "Too many tries. Wait a minute, then try again.",
    PORTAL_USER_INACTIVE: "This access has been switched off. Ask your account manager.",
    USER_INACTIVE: "This access has been switched off. Ask your account manager.",
    INVALID_TOKEN: "This link has expired or was already used. Ask for a new one.",
    TOKEN_EXPIRED: "This link has expired or was already used. Ask for a new one.",
    INVALID_INVITE: "This invitation has expired or was already used. Ask for a new one.",
    WEAK_PASSWORD: "Choose a stronger password.",
    BREACHED_PASSWORD: "This password has appeared in a data breach. Choose another.",
    SESSION_EXPIRED: "Your session has ended. Please sign in again.",
    SESSION_REVOKED: "Your session has ended. Please sign in again.",
    AUTH_REQUIRED: "Please sign in again.",
    REAUTH_REQUIRED: "Please sign in again to do this.",
    WEBAUTHN_VERIFICATION_FAILED: "Your device couldn’t be verified. Try again.",
    INVALID_CHALLENGE: "Your device couldn’t be verified. Try again.",
    PASSKEY_REVOKED: "This device is no longer set up. Sign in with a code.",
    PASSKEY_LIMIT: "Too many devices are set up. Remove one first.",
    CREDENTIAL_TAKEN: "This device is already set up.",
    NOT_FOUND: "We couldn’t find that. It may have been removed.",
    PORTAL_SCOPE: "Your access doesn’t include this.",
    PORTAL_FORBIDDEN: "Your access doesn’t include this.",
    FORBIDDEN: "Your access doesn’t include this.",
    PORTAL_ADMIN_REQUIRED: "Only your company’s admins can do this.",
    FILE_REQUIRED: "Add a photo or a PDF first.",
    BAD_FILE: "This file can’t be read. Send a PDF, JPG or PNG.",
    FILE_TOO_LARGE: "This file is too large.",
    REQUEST_CLOSED: "This request is already closed.",
    ALREADY_ANSWERED: "This has already been answered.",
    BAD_AMOUNT: "Enter the amount you paid.",
    BAD_DATE: "The payment date can’t be in the future.",
    BAD_METHOD: "Choose how you paid.",
    ALLOCATION_EXCEEDS: "The invoices add up to more than the amount paid.",
    ALREADY_IN_TEAM: "This person already has access.",
    EMAIL_TAKEN: "This person already has access.",
    OTHER_COMPANY: "This email is already on another company’s account.",
    LAST_ADMIN: "Your company needs at least one admin.",
    SELF_REMOVE: "You can’t remove yourself.",
    SELF_SCOPE: "You can’t change your own access.",
    BAD_SCOPE: "Choose one of the three access levels.",
    BAD_DOC_TYPE: "Choose what kind of document this is.",
    MILESTONE_MISMATCH: "That step isn’t on this shipment.",
    VALIDATION_ERROR: "Some details are missing or not valid.",
    FEATURE_DISABLED: "This isn’t available yet.",
    TENANT_SUSPENDED: "The portal is unavailable right now.",
    TENANT_NOT_READY: "The portal is unavailable right now.",
    DOWNLOAD_FAILED: "The download didn’t work. Try again.",
    EMPTY_MESSAGE: "Write something, or attach a photo, a file or a location.",
    VOICE_TOO_LONG: "Voice notes can be up to 5 minutes.",
    PROPOSAL_ANSWERED: "This proposal has already been answered.",
    PROPOSAL_EXPIRED: "This proposal is no longer valid. Ask for an updated one.",
    ESIGN_UNAVAILABLE: "Online signing isn’t available for this proposal.",
    SIGNATURE_REQUIRED: "This proposal is accepted by signing it.",
    SIGNING_CLOSED: "This signature request is closed. Reload the proposal.",
    SIGNING_NOT_STARTED: "Ask for a code first.",
    NO_SENDER: "This proposal can’t be signed online. Contact your account manager.",
    OTP_INVALID: "That code isn’t right. Check the email and try again.",
    OTP_EXPIRED: "That code has expired. Send a new one.",
    OTP_EXHAUSTED: "Too many wrong codes. Send a new one.",
    OTP_NOT_ISSUED: "Ask for a code first.",
    OTP_COOLDOWN: "Too many codes sent. Wait a while, then try again.",
    OTP_REQUIRED: "Enter the code we emailed you first.",
    DOCUMENT_AMENDED: "This proposal changed after the code was sent. Reload it and sign again.",
    ALREADY_SIGNED: "You have already signed this.",
    UNKNOWN_DECLINE_REASON: "Choose a reason from the list.",
    INVALID_SUBSCRIPTION: "This device could not be registered for notifications. Try again.",
    BUNDLE_TOO_LARGE: "These are too large to download together. Download them one by one.",
  },
  upload: {
    takePhoto: "Take a photo",
    chooseFile: "Choose a file",
    preparing: "Preparing…",
    sending: "Sending…",
    complete: "Upload complete",
    remove: "Remove file",
    was: "was {{size}}",
    badType: "Send a PDF, JPG, PNG or WebP.",
    tooBig: "This file is over {{limit}}.",
    unreadable: "This file couldn’t be read.",
  },
  chat: {
    open: "Open messages",
    title: "Messages",
    placeholder: "Write a message",
    caption: "Add a caption",
    send: "Send",
    emptyTitle: "Say hello",
    emptyHint: "The team handling your cargo replies here.",
    team: "Your team",
    thisShipment: "This shipment",
    untag: "Not about this shipment",
    retry: "Not sent — tap to retry",
    general: "General",
    generalHint: "Ask us anything",
    shipment: "Shipment",
    all: "All conversations",
    newAbout: "Message about a shipment",
    pickShipment: "Which shipment?",
    noShipments: "No active shipments",
    you: "You",
    unread: "Unread: {{count}}",
    earlier: "Earlier messages",
    newMessages: "New messages",
    sending: "Sending",
    sent: "Sent",
    seen: "Seen",
    aboutStage: "About: {{stage}}",
    removeStage: "Not about this step",
    attach: "Attach",
    takePhoto: "Take a photo",
    photosFiles: "Photos & PDFs",
    location: "Location",
    removeFile: "Remove {{name}}",
    tooMany: "Up to 10 files at a time.",
    locating: "Finding where you are…",
    locationLabel: "What is here? (optional)",
    locationPlaceholder: "Warehouse gate B",
    sendLocation: "Send this location",
    locationOff: "Location is off for this site. Allow it in your browser’s settings.",
    locationFailed: "Your location couldn’t be found. Try again outside or near a window.",
    openMap: "Open in Maps",
    record: "Record a voice note",
    recording: "Recording",
    sendVoice: "Send voice note",
    deleteVoice: "Delete recording",
    micOff: "The microphone is off for this site. Allow it in your browser’s settings.",
    micUnsupported: "This browser can’t record voice notes.",
    play: "Play voice note",
    pause: "Pause",
    download: "Download {{name}}",
    viewPhoto: "Open photo",
    photo: "Photo",
    downloadOriginal: "Download original",
    kind: {
      IMAGE: "Photo",
      FILE: "File",
      VOICE: "Voice note",
      LOCATION: "Location",
    },
  },
  home: {
    greet: {
      morning: "Good morning, {{name}}",
      afternoon: "Good afternoon, {{name}}",
      evening: "Good evening, {{name}}",
    },
    hello: {
      morning: "Good morning",
      afternoon: "Good afternoon",
      evening: "Good evening",
    },
    needsYou: "Needs you",
    glance: "At a glance",
    onTheMove: "On the move",
    toPay: "To pay",
    toSend: "To send",
    moving: "On the move",
    noneMoving: "Nothing on the move right now",
    allClear: "You’re all caught up",
    shortcuts: "Quick actions",
  },
  ship: {
    filter: "Show",
    active: "On the move",
    delivered: "Delivered",
    search: "Search shipments",
    noMatch: "Nothing matches",
    noneActive: "No shipments on the move",
    noneDone: "No delivered shipments yet",
    eta: "ETA {{when}}",
    arrived: "Arrived {{when}}",
    done: "Delivered",
    allDone: "All steps done",
    settingUp: "Being set up",
    needsYou: "To send: {{count}}",
    progress: "Progress",
    unknownPlace: "—",
    details: "Shipment details",
    message: "Message the team",
    messageShort: "Message",
    journey: "Journey",
    expected: "Expected {{when}}",
    skipped: "Not needed",
    onHold: "On hold",
    boxes: "Containers: {{count}}",
    service: "Service",
    from: "From",
    to: "To",
    vessel: "Vessel or flight",
    transportRef: "BL / AWB",
    containers: "Containers",
    assumptions: "What the dates assume",
  },
  req: {
    status: {
      OPEN: "Needed",
      REJECTED: "Sent back",
      SUBMITTED: "In review",
      ACCEPTED: "Accepted",
      CANCELLED: "Cancelled",
    },
    due: "Due {{when}}",
    upload: "Upload",
    answer: "Answer",
    again: "Send again",
    sent: "Sent — thank you",
    replace: "Replace file",
    replaceTitle: "Send a better copy?",
    send: "Send document",
    sendAnswer: "Send answer",
    sentBack: "Why it was sent back",
    fromTeam: "Note from the team",
    acceptedHint: "Checked and accepted",
    reviewHint: "We’re checking it",
    yourAnswer: "Your answer",
  },
  share: {
    title: "Send a document",
    short: "Send",
    what: "What is it?",
    more: "More…",
    other: "Something else",
    which: "Which shipment?",
    noShipment: "None",
    file: "The file",
    note: "Add a note (optional)",
    send: "Send",
    sent: "Document sent",
  },
  ask: {
    title: "Ask a question",
    short: "Ask",
    aboutStep: "Ask about this step",
    aboutThis: "Ask about {{step}}",
    chatInstead: "Message the team instead",
    quick: {
      when: "When will this be done?",
      needMe: "Do you need anything from me?",
      faster: "Can this go faster?",
      other: "Something else",
    },
    yourQuestion: "Your question",
    addDetail: "Anything to add? (optional)",
    send: "Send question",
    sent: "Question sent to the team",
    yours: "Your questions",
    question: "Question",
    reply: "Reply",
    status: {
      OPEN: "Sent",
      IN_PROGRESS: "Answered",
      RESOLVED: "Resolved",
    },
  },
  bill: {
    toPay: "To pay",
    nothingDue: "All paid",
    ivePaid: "I’ve paid",
    pay: "Pay",
    overdueAmount: "{{amount}} overdue",
    inReviewCount: "In review: {{count}}",
    howToPay: "How to pay",
    howToPayHint:
      "Put the invoice number in your transfer reference, then tap “I’ve paid” and add the receipt.",
    holder: "Account holder",
    account: "Account number",
    iban: "IBAN",
    swift: "SWIFT / BIC",
    filter: "Show",
    tab: {
      open: "To pay",
      paid: "Paid",
      payments: "My payments",
    },
    allClear: "Nothing to pay",
    noPaid: "No paid invoices yet",
    noProofs: "No payments sent yet",
    invoice: "Invoice",
    invoices: "Invoices",
    dueWhen: "Due {{when}}",
    wasDue: "Was due {{when}}",
    state: {
      DUE: "Due",
      OVERDUE: "Overdue",
      PART_PAID: "Part paid",
      PAID: "Paid",
      IN_REVIEW: "In review",
      CANCELLED: "Cancelled",
    },
    ofTotal: "of {{total}}",
    leftToPay: "Left to pay",
    total: "Total",
    paidAmount: "Paid {{amount}}",
    inReviewAmount: "In review {{amount}}",
    issued: "Issued",
    dueOn: "Due",
    lines: "What it covers",
    atCost: "at cost",
    services: "Services (excl. VAT)",
    disbursements: "Disbursements",
    vat: "VAT",
    receiptFile: "payment-proof",
    docs: {
      title: "Supporting documents",
      count: "Supporting documents: {{count}}",
      shared: "Shared {{when}}",
      all: "Download all (.zip)",
      show: "See the files",
      hide: "Hide the files",
      downloadOne: "Download {{name}}",
      about: "About these documents",
      info:
        "The receipts behind the costs this invoice bills at cost. The ZIP holds the invoice and every document, numbered in the order of its lines.",
      zipName: "documents",
    },
    proof: {
      SUBMITTED: "In review",
      CONFIRMED: "Confirmed",
      REJECTED: "Not confirmed",
    },
  },
  pay: {
    step1: "What are you paying?",
    step2: "How did you pay?",
    step3: "Add the receipt",
    progress: "Step {{step}} of {{total}}",
    which: "Invoices",
    amount: "Amount paid",
    oneCurrency: "Pick invoices in one currency.",
    moreThanPicked: "More than the invoices picked — finance will allocate the rest.",
    how: "Method",
    method: {
      BANK: "Bank transfer",
      MOBILE_MONEY: "Mobile money",
      CASH: "Cash",
      CHEQUE: "Cheque",
    },
    wallet: "Which wallet?",
    otherWallet: "Other",
    when: "When?",
    day: {
      today: "Today",
      yesterday: "Yesterday",
      other: "Another day",
    },
    reference: "Reference (optional)",
    txId: "Transaction ID (optional)",
    chequeNo: "Cheque number (optional)",
    note: "Note (optional)",
    send: "Send proof",
    sent: "Sent — finance will confirm it",
  },
  quote: {
    request: "Request a quote",
    new: "New quote",
    none: "No quote requests yet",
    step1: "How should it move?",
    step2: "From where to where?",
    step3: "What are you shipping?",
    dir: {
      IMPORT: "Import",
      EXPORT: "Export",
      LOCAL: "In-country",
    },
    from: "From",
    to: "To",
    sameAsLast: "Same as last time",
    likeShipment: "Like {{ref}}",
    describe: "Describe it in your own words",
    describeHint: "e.g. 2×40HC of tiles, Shanghai to Douala, FOB, about 48 t",
    fill: "Fill it in for me",
    filling: "Reading your description…",
    filled: "Filled in — check each step before sending",
    filledPill: "Filled for you",
    tab: {
      requests: "Requests",
      proposals: "Proposals",
    },
    // The route step: the two ends of the main leg, named for the mode, and
    // the two optional doors either side of it.
    route: {
      pol: "Port of loading",
      pod: "Port of discharge",
      portHint: "Search a port",
      aol: "Origin airport",
      aod: "Destination airport",
      airportHint: "Search an airport",
      placeHint: "City, port or address",
      collection: "Place of collection",
      collectionAdd: "We collect it",
      collectionAddHint: "From a factory, a supplier or any address",
      delivery: "Place of delivery",
      deliveryAdd: "We deliver it",
      deliveryAddHint: "To your warehouse or any address",
      doorHint: "Address, town or warehouse",
      remove: "Remove {{place}}",
      doorToDoor: "Door to door",
      withCollection: "Collection included",
      withDelivery: "Delivery included",
    },
    incoterm: "Incoterm",
    notSure: "Not sure",
    what: "What is it?",
    whatHint: "e.g. 2 pallets of spare parts",
    weight: "Approx. weight (optional)",
    send: "Send request",
    sent: "Request sent — we’ll come back with a price",
    status: {
      RECEIVED: "Received",
      UNDER_REVIEW: "Being priced",
      CLARIFICATION_REQUIRED: "Needs detail",
      QUOTED: "Quoted",
      CONVERTED_TO_OPPORTUNITY: "In progress",
      CLOSED_NO_ACTION: "Closed",
    },
  },
  // The place picker (ui/place-picker.tsx): a port, an airport, a town or a door.
  place: {
    search: "Search",
    clear: "Clear",
    change: "Change",
    recent: "Your places",
    popular: "Popular",
    matches: "Ports, airports and towns",
    world: "Addresses and places worldwide",
    worldNote: "We confirm the exact spot when you send",
    searchWorld: "Search worldwide for “{{term}}”",
    searchingWorld: "Searching addresses…",
    searching: "Searching…",
    useTyped: "Use “{{term}}” as written",
    useTypedHint: "We’ll find it on the map for you",
    typed: "As written — we’ll pin it",
    none: "Nothing matches yet",
    unavailable: "Address search is unavailable right now. Write the place and we’ll pin it.",
    failed: "Search did not answer. Write the place and we’ll pin it.",
    results: "Places found: {{count}}",
    kind: {
      SEAPORT: "Seaport",
      AIRPORT: "Airport",
      TERMINAL: "Terminal",
      RAIL_TERMINAL: "Rail terminal",
      BORDER_POST: "Border post",
      WAREHOUSE: "Warehouse",
      INLAND: "Inland depot",
      CITY: "Town",
      ADDRESS: "Address",
      OTHER: "Place",
    },
  },
  prop: {
    proposal: "Proposal",
    status: {
      SENT: "Waiting for your answer",
      ACCEPTED: "Accepted",
      REJECTED: "Declined",
    },
    expired: "No longer valid",
    validUntil: "Valid until {{date}}",
    total: "Total",
    pricing: "Pricing",
    accept: "Accept",
    acceptSign: "Accept and sign",
    decline: "Decline",
    acceptTitle: "Accept this proposal?",
    acceptBody: "Your acceptance is recorded with your name and the time, and the team is told at once.",
    accepted: "Accepted — thank you. The team will be in touch.",
    declined: "Declined — the team will be in touch.",
    declineTitle: "Why are you declining?",
    declineNote: "Anything to add? (optional)",
    declineSend: "Decline the proposal",
    awaiting: "A proposal is waiting for your answer",
    awaitingCount: "Waiting: {{count}}",
    review: "Review",
    sign: {
      step1: "Confirm it’s you",
      step2: "Sign",
      sending: "Sending you a code…",
      sentTo: "We sent a 6-digit code to {{email}}.",
      codeLabel: "Signing code",
      resend: "Send a new code",
      resent: "A new code is on its way",
      how: "How do you want to sign?",
      card: {
        STAMP: "Stamp with my name",
        DRAWN: "Draw my signature",
      },
      name: "Your name",
      role: "Your role (optional)",
      rolePlaceholder: "Finance Manager",
      draw: "Sign here",
      clear: "Clear",
      agree: "Signing accepts this proposal and its terms.",
      aboutTitle: "About this signature",
      about:
        "Your email is confirmed by the code; your name and role are as you typed them. Both go on the signature certificate, which anyone holding the document can verify with its code.",
      submit: "Sign and accept",
      signedBy: "Signed by {{name}}",
      verify: "Verification code",
    },
  },
  docs: {
    filter: "Show",
    toSend: "To send",
    sent: "Sent",
    library: "Library",
    nothingToSend: "Nothing to send — all done",
    nothingSent: "Nothing sent yet",
    none: "No documents yet",
    search: "Search documents",
    general: "Company documents",
    document: "Document",
  },
  team: {
    title: "Team",
    invite: "Invite",
    inviteTitle: "Invite a colleague",
    name: "Name",
    nameHint: "It greets them, and shows on every message and file they send.",
    access: "Access",
    scope: {
      ALL: "Everything",
      OPERATIONS: "Shipments & documents",
      BILLING: "Billing",
    },
    scopeHint: {
      ALL: "Shipments, documents and billing",
      OPERATIONS: "No invoices or payments",
      BILLING: "Invoices and payments only",
    },
    makeAdmin: "Can manage the team",
    adminHint: "Invite, change and remove colleagues",
    admin: "Admin",
    sendInvite: "Send invitation",
    inviteSent: "Invitation sent to {{email}}",
    invited: "Invited",
    you: "You",
    saved: "Saved",
    remove: "Remove from team",
    removeTitle: "Remove {{name}}?",
    removeBody: "They lose access straight away. You can invite them again later.",
    removed: "Removed from the team",
  },
  account: {
    editName: "Edit your name",
    nameTitle: "Your name",
    nameLabel: "Full name",
    nameBody: "It greets you here and shows on every message, document and payment you send, so the team knows who they are talking to.",
    nameSaved: "Name saved",
    addName: "Add your name",
    security: "Security",
    device: "Device",
    thisDevice: "This device",
    lastSeen: "Last seen {{when}}",
    signOutDevice: "Sign out",
    deviceOutTitle: "Sign out this device?",
    deviceOut: "Device signed out",
    preferences: "Preferences",
    language: "Language",
    theme: "Appearance",
    light: "Light",
    dark: "Dark",
    auto: "Auto",
    signOut: "Sign out",
    signOutForget: "Sign out and forget this device",
    signOutTitle: "Sign out?",
    forgetTitle: "Forget this device?",
    forgetBody: "Next time, you’ll start from your email.",
    portal: "Portal",
  },
  notify: {
    title: "Notifications",
    thisDevice: "This device",
    state: {
      on: "On — we’ll tell you here",
      off: "Off",
      blocked: "Blocked for this site",
      unsupported: "Not available in this browser",
      installFirst: "Add the portal to your Home Screen first",
      unconfigured: "Not set up yet",
    },
    switchLabel: "Notifications on this device",
    turnedOn: "Notifications are on",
    turnedOff: "Notifications are off on this device",
    test: "Send a test",
    testSent: "Test sent — check your notifications",
    testNone: "No device answered — turn notifications off and on again",
    email: "Email",
    push: "App",
    topic: {
      MESSAGES: "Messages from the team",
      REQUESTS: "Documents we need",
      BILLING: "Invoices and payments",
      PROPOSALS: "Proposals",
      SHIPMENTS: "Shipment steps",
    },
    saved: "Saved",
    infoLabel: "How notifications work",
    infoTitle: "How we tell you",
    info1:
      "In the app, the moment something needs you: a reply, a document we need, a new invoice or proposal, a shipment moving.",
    info2:
      "By email, a reply only if it is still unread ten minutes later — at most once an hour per conversation.",
    info3: "Shipment steps by email start off. Turn them on if you want them.",
    blockedTitle: "Notifications are blocked",
    blockedHow:
      "They were refused for this site. Allow them in the browser’s site settings — the padlock next to the address — then come back here.",
  },
  install: {
    title: "Install the app",
    hint: "Opens like an app, with notifications",
    button: "Install",
    done: "Installed",
    howLabel: "How to install",
    iosTitle: "Add to your Home Screen",
    ios1: "Tap the Share button in Safari.",
    ios2: "Choose “Add to Home Screen”.",
    ios3: "Open the portal from its new icon, then turn on notifications here.",
  },
  fin: {
    title: "Financial position",
    period: "{{from}} – {{to}} · OHADA",
    revenue: "Revenue",
    netResult: "Net result",
    cash: "Cash on hand",
    bsTotal: "Balance sheet total",
    incomeStatement: "Income statement",
    produits: "Income",
    charges: "Expenses",
    hao: "Non-ordinary items (net)",
    balanceSheet: "Balance sheet",
    actif: "Assets",
    passif: "Liabilities",
    result: "Result",
    total: "Total",
    unbalanced: "Assets and liabilities don’t balance for this period — the figures are provisional.",
    cashPosition: "Cash position",
    noTreasury: "No treasury accounts",
  },
  audit: {
    title: "Audit room",
    until: "Access until {{date}}",
    trialBalance: "Trial balance",
    account: "Account",
    debit: "Debit",
    credit: "Credit",
    noMovements: "No movements this period",
    trail: "Audit trail",
    noPostings: "No postings this period",
    system: "System",
    dataRoom: "Data room",
    ask: "Request a document",
    what: "What do you need, and for which period or file?",
    send: "Send request",
    asked: "Request sent",
    noRequests: "No requests yet",
    noDocs: "No documents shared yet",
    room: {
      OPEN: "Waiting",
      ANSWERED: "Answered",
    },
  },
} as const;

export const fr = {
  brandFallback: "Portail client",
  offline: "Vous êtes hors ligne. Vérifiez votre connexion et réessayez.",
  nav: {
    label: "Navigation principale",
    home: "Accueil",
    shipments: "Expéditions",
    quotes: "Devis",
    billing: "Factures",
    documents: "Documents",
    account: "Compte",
  },
  common: {
    back: "Retour",
    close: "Fermer",
    notNow: "Plus tard",
    retry: "Réessayer",
    loading: "Chargement",
    seeAll: "Tout voir",
    cancel: "Annuler",
    save: "Enregistrer",
    next: "Suivant",
    download: "Télécharger",
    pdf: "PDF",
    copy: "Copier",
    copied: "Copié",
    clear: "Effacer",
    calendar: "Ouvrir le calendrier",
    datePlaceholder: "jj/mm/aaaa",
  },
  kind: {
    CLIENT: "Client",
    INVESTOR: "Investisseur",
    AUDITOR: "Auditeur",
  },
  mode: {
    SEA: "Fret maritime",
    AIR: "Fret aérien",
    ROAD: "Route",
    RAIL: "Rail",
    STORAGE: "Entreposage",
    CUSTOMS: "Dédouanement",
    OTHER: "Autre",
  },
  signin: {
    title: "Connexion",
    sub: "Vos expéditions, documents et factures.",
    eyebrow: "Espace client",
    taglineMain: "Tout sur vos marchandises,",
    taglineAccent: "au même endroit.",
    trackLink: "Suivre une expédition sans vous connecter",
    themeDark: "Passer en mode sombre",
    themeLight: "Passer en mode clair",
    whatsInside: "Ce que vous y trouverez",
    feature: {
      track: "Suivez chaque expédition, étape par étape",
      documents: "Téléchargez vos documents et factures",
      send: "Envoyez les documents demandés depuis votre téléphone",
      pay: "Voyez ce qui est dû et envoyez vos preuves de paiement",
      chat: "Écrivez à l’équipe qui traite vos marchandises",
      team: "Invitez vos collègues",
    },
    accessNote: "L’accès se fait sur invitation de votre chargé de compte.",
    email: "E-mail",
    emailPlaceholder: "vous@entreprise.com",
    continue: "Continuer",
    usePassword: "Utiliser mon mot de passe",
    emailMeCode: "Recevoir un code par e-mail",
    welcomeBackNamed: "Bon retour, {{name}}",
    welcomeBack: "Bon retour",
    notYou: "Vous n’êtes pas {{email}} ?",
    keep: "Rester connecté",
    keepHint: "Sur cet appareil, pendant 30 jours",
    checkEmail: "Consultez vos e-mails",
    codeSent: "Nous avons envoyé un code à 6 chiffres à {{email}}",
    codeLabel: "Code de connexion",
    digit: "Chiffre {{n}}",
    resend: "Renvoyer un code",
    resendIn: "Nouveau code dans {{s}} s",
    checking: "Vérification…",
    passwordTitle: "Saisissez votre mot de passe",
    password: "Mot de passe",
    signIn: "Se connecter",
    forgot: "Mot de passe oublié ?",
    resetSent: "Si cette adresse a un accès, un lien pour choisir un nouveau mot de passe vous a été envoyé.",
    back: "Retour",
    showPassword: "Afficher le mot de passe",
    hidePassword: "Masquer le mot de passe",
    bio: {
      face: "Continuer avec Face ID",
      touch: "Continuer avec Touch ID",
      hello: "Continuer avec Windows Hello",
      finger: "Continuer avec l’empreinte",
    },
  },
  setPassword: {
    title: "Choisissez votre mot de passe",
    sub: "Vous l’utiliserez avec votre e-mail pour vous connecter.",
    new: "Nouveau mot de passe",
    confirm: "Saisissez-le à nouveau",
    mismatch: "Les deux mots de passe ne correspondent pas.",
    cta: "Enregistrer et se connecter",
    badLinkTitle: "Ce lien ne fonctionne pas",
    badLink: "Utilisez le lien tel qu’il figure dans votre e-mail, ou demandez-en un nouveau.",
    rule: {
      length: "12 caractères ou plus",
      upper: "Une majuscule",
      lower: "Une minuscule",
      digit: "Un chiffre",
      symbol: "Un symbole",
    },
  },
  passkey: {
    offerTitle: {
      face: "Utiliser Face ID la prochaine fois ?",
      touch: "Utiliser Touch ID la prochaine fois ?",
      hello: "Utiliser Windows Hello la prochaine fois ?",
      finger: "Utiliser votre empreinte la prochaine fois ?",
    },
    offerBody: "Un geste pour vous connecter — sans code ni mot de passe.",
    turnOn: "Activer",
    on: {
      face: "Face ID est activé",
      touch: "Touch ID est activé",
      hello: "Windows Hello est activé",
      finger: "Connexion par empreinte activée",
    },
    off: "Désactivé sur cet appareil",
    label: {
      face: "Face ID",
      touch: "Touch ID",
      hello: "Windows Hello",
      finger: "Empreinte digitale",
    },
    thisDevice: "Sur cet appareil",
  },
  noAccess: {
    title: "Aucun accès actif",
    hint: "Votre accès a pris fin ou a été désactivé. Votre chargé de compte peut le rétablir.",
  },
  err: {
    generic: "Un problème est survenu. Veuillez réessayer.",
    BAD_CREDENTIALS: "Cet e-mail et ce mot de passe ne correspondent pas.",
    INVALID_CODE: "Ce code est incorrect ou a expiré.",
    RATE_LIMITED: "Trop de tentatives. Patientez une minute, puis réessayez.",
    PORTAL_USER_INACTIVE: "Cet accès a été désactivé. Contactez votre chargé de compte.",
    USER_INACTIVE: "Cet accès a été désactivé. Contactez votre chargé de compte.",
    INVALID_TOKEN: "Ce lien a expiré ou a déjà servi. Demandez-en un nouveau.",
    TOKEN_EXPIRED: "Ce lien a expiré ou a déjà servi. Demandez-en un nouveau.",
    INVALID_INVITE: "Cette invitation a expiré ou a déjà servi. Demandez-en une nouvelle.",
    WEAK_PASSWORD: "Choisissez un mot de passe plus robuste.",
    BREACHED_PASSWORD: "Ce mot de passe figure dans une fuite de données. Choisissez-en un autre.",
    SESSION_EXPIRED: "Votre session a pris fin. Veuillez vous reconnecter.",
    SESSION_REVOKED: "Votre session a pris fin. Veuillez vous reconnecter.",
    AUTH_REQUIRED: "Veuillez vous reconnecter.",
    REAUTH_REQUIRED: "Veuillez vous reconnecter pour effectuer cette action.",
    WEBAUTHN_VERIFICATION_FAILED: "Votre appareil n’a pas pu être vérifié. Réessayez.",
    INVALID_CHALLENGE: "Votre appareil n’a pas pu être vérifié. Réessayez.",
    PASSKEY_REVOKED: "Cet appareil n’est plus configuré. Connectez-vous avec un code.",
    PASSKEY_LIMIT: "Trop d’appareils sont configurés. Retirez-en un d’abord.",
    CREDENTIAL_TAKEN: "Cet appareil est déjà configuré.",
    NOT_FOUND: "Élément introuvable. Il a peut-être été retiré.",
    PORTAL_SCOPE: "Votre accès ne couvre pas cette partie.",
    PORTAL_FORBIDDEN: "Votre accès ne couvre pas cette partie.",
    FORBIDDEN: "Votre accès ne couvre pas cette partie.",
    PORTAL_ADMIN_REQUIRED: "Seuls les administrateurs de votre entreprise peuvent le faire.",
    FILE_REQUIRED: "Ajoutez d’abord une photo ou un PDF.",
    BAD_FILE: "Ce fichier est illisible. Envoyez un PDF, un JPG ou un PNG.",
    FILE_TOO_LARGE: "Ce fichier est trop volumineux.",
    REQUEST_CLOSED: "Cette demande est déjà close.",
    ALREADY_ANSWERED: "Une réponse a déjà été donnée.",
    BAD_AMOUNT: "Saisissez le montant payé.",
    BAD_DATE: "La date du paiement ne peut pas être dans le futur.",
    BAD_METHOD: "Indiquez comment vous avez payé.",
    ALLOCATION_EXCEEDS: "Les factures dépassent le montant payé.",
    ALREADY_IN_TEAM: "Cette personne a déjà un accès.",
    EMAIL_TAKEN: "Cette personne a déjà un accès.",
    OTHER_COMPANY: "Cet e-mail est déjà rattaché au compte d’une autre entreprise.",
    LAST_ADMIN: "Votre entreprise doit garder au moins un administrateur.",
    SELF_REMOVE: "Vous ne pouvez pas vous retirer vous-même.",
    SELF_SCOPE: "Vous ne pouvez pas modifier votre propre accès.",
    BAD_SCOPE: "Choisissez l’un des trois niveaux d’accès.",
    BAD_DOC_TYPE: "Indiquez le type de document.",
    MILESTONE_MISMATCH: "Cette étape ne fait pas partie de cette expédition.",
    VALIDATION_ERROR: "Certaines informations manquent ou sont invalides.",
    FEATURE_DISABLED: "Ce n’est pas encore disponible.",
    TENANT_SUSPENDED: "Le portail est indisponible pour le moment.",
    TENANT_NOT_READY: "Le portail est indisponible pour le moment.",
    DOWNLOAD_FAILED: "Le téléchargement a échoué. Réessayez.",
    EMPTY_MESSAGE: "Écrivez quelque chose, ou joignez une photo, un fichier ou une position.",
    VOICE_TOO_LONG: "Les messages vocaux sont limités à 5 minutes.",
    PROPOSAL_ANSWERED: "Cette proposition a déjà reçu une réponse.",
    PROPOSAL_EXPIRED: "Cette proposition n’est plus valable. Demandez-en une mise à jour.",
    ESIGN_UNAVAILABLE: "La signature en ligne n’est pas disponible pour cette proposition.",
    SIGNATURE_REQUIRED: "Cette proposition s’accepte en la signant.",
    SIGNING_CLOSED: "Cette demande de signature est close. Rechargez la proposition.",
    SIGNING_NOT_STARTED: "Demandez d’abord un code.",
    NO_SENDER: "Cette proposition ne peut pas être signée en ligne. Contactez votre chargé de compte.",
    OTP_INVALID: "Ce code est incorrect. Vérifiez l’e-mail et réessayez.",
    OTP_EXPIRED: "Ce code a expiré. Demandez-en un nouveau.",
    OTP_EXHAUSTED: "Trop de codes erronés. Demandez-en un nouveau.",
    OTP_NOT_ISSUED: "Demandez d’abord un code.",
    OTP_COOLDOWN: "Trop de codes envoyés. Patientez un moment, puis réessayez.",
    OTP_REQUIRED: "Saisissez d’abord le code reçu par e-mail.",
    DOCUMENT_AMENDED: "Cette proposition a changé après l’envoi du code. Rechargez-la et signez de nouveau.",
    ALREADY_SIGNED: "Vous avez déjà signé.",
    UNKNOWN_DECLINE_REASON: "Choisissez un motif dans la liste.",
    INVALID_SUBSCRIPTION: "Cet appareil n’a pas pu être inscrit aux notifications. Réessayez.",
    BUNDLE_TOO_LARGE:
      "Ces fichiers sont trop volumineux pour un seul téléchargement. Téléchargez-les un par un.",
  },
  upload: {
    takePhoto: "Prendre une photo",
    chooseFile: "Choisir un fichier",
    preparing: "Préparation…",
    sending: "Envoi…",
    complete: "Envoi terminé",
    remove: "Retirer le fichier",
    was: "au lieu de {{size}}",
    badType: "Envoyez un PDF, un JPG, un PNG ou un WebP.",
    tooBig: "Ce fichier dépasse {{limit}}.",
    unreadable: "Ce fichier n’a pas pu être lu.",
  },
  chat: {
    open: "Ouvrir les messages",
    title: "Messages",
    placeholder: "Écrire un message",
    caption: "Ajouter une légende",
    send: "Envoyer",
    emptyTitle: "Dites bonjour",
    emptyHint: "L’équipe qui traite vos marchandises vous répond ici.",
    team: "Votre équipe",
    thisShipment: "Cette expédition",
    untag: "Sans lien avec cette expédition",
    retry: "Non envoyé — touchez pour réessayer",
    general: "Général",
    generalHint: "Posez-nous vos questions",
    shipment: "Expédition",
    all: "Toutes les conversations",
    newAbout: "Écrire au sujet d’une expédition",
    pickShipment: "Quelle expédition ?",
    noShipments: "Aucune expédition en cours",
    you: "Vous",
    unread: "Non lus : {{count}}",
    earlier: "Messages précédents",
    newMessages: "Nouveaux messages",
    sending: "Envoi",
    sent: "Envoyé",
    seen: "Vu",
    aboutStage: "Au sujet de : {{stage}}",
    removeStage: "Sans lien avec cette étape",
    attach: "Joindre",
    takePhoto: "Prendre une photo",
    photosFiles: "Photos et PDF",
    location: "Position",
    removeFile: "Retirer {{name}}",
    tooMany: "Jusqu’à 10 fichiers à la fois.",
    locating: "Recherche de votre position…",
    locationLabel: "Qu’y a-t-il ici ? (facultatif)",
    locationPlaceholder: "Entrepôt, portail B",
    sendLocation: "Envoyer cette position",
    locationOff: "La localisation est désactivée pour ce site. Autorisez-la dans les réglages du navigateur.",
    locationFailed: "Votre position est introuvable. Réessayez à l’extérieur ou près d’une fenêtre.",
    openMap: "Ouvrir dans Plans",
    record: "Enregistrer un message vocal",
    recording: "Enregistrement",
    sendVoice: "Envoyer le message vocal",
    deleteVoice: "Supprimer l’enregistrement",
    micOff: "Le micro est désactivé pour ce site. Autorisez-le dans les réglages du navigateur.",
    micUnsupported: "Ce navigateur ne peut pas enregistrer de messages vocaux.",
    play: "Écouter le message vocal",
    pause: "Pause",
    download: "Télécharger {{name}}",
    viewPhoto: "Ouvrir la photo",
    photo: "Photo",
    downloadOriginal: "Télécharger l’original",
    kind: {
      IMAGE: "Photo",
      FILE: "Fichier",
      VOICE: "Message vocal",
      LOCATION: "Position",
    },
  },
  home: {
    greet: {
      morning: "Bonjour {{name}}",
      afternoon: "Bon après-midi {{name}}",
      evening: "Bonsoir {{name}}",
    },
    hello: {
      morning: "Bonjour",
      afternoon: "Bon après-midi",
      evening: "Bonsoir",
    },
    needsYou: "À faire",
    glance: "En un coup d’œil",
    onTheMove: "En cours",
    toPay: "À payer",
    toSend: "À envoyer",
    moving: "En cours",
    noneMoving: "Aucune expédition en cours",
    allClear: "Tout est à jour",
    shortcuts: "Raccourcis",
  },
  ship: {
    filter: "Afficher",
    active: "En cours",
    delivered: "Livrées",
    search: "Rechercher une expédition",
    noMatch: "Aucun résultat",
    noneActive: "Aucune expédition en cours",
    noneDone: "Aucune expédition livrée pour l’instant",
    eta: "Arrivée {{when}}",
    arrived: "Arrivée {{when}}",
    done: "Livrée",
    allDone: "Toutes les étapes terminées",
    settingUp: "En préparation",
    needsYou: "À envoyer : {{count}}",
    progress: "Avancement",
    unknownPlace: "—",
    details: "Détails de l’expédition",
    message: "Écrire à l’équipe",
    messageShort: "Écrire",
    journey: "Parcours",
    expected: "Prévu {{when}}",
    skipped: "Non requise",
    onHold: "En attente",
    boxes: "Conteneurs : {{count}}",
    service: "Prestation",
    from: "Départ",
    to: "Arrivée",
    vessel: "Navire ou vol",
    transportRef: "BL / LTA",
    containers: "Conteneurs",
    assumptions: "Hypothèses du calendrier",
  },
  req: {
    status: {
      OPEN: "À fournir",
      REJECTED: "Refusé",
      SUBMITTED: "En vérification",
      ACCEPTED: "Accepté",
      CANCELLED: "Annulé",
    },
    due: "Échéance {{when}}",
    upload: "Envoyer",
    answer: "Répondre",
    again: "Renvoyer",
    sent: "Envoyé — merci",
    replace: "Remplacer le fichier",
    replaceTitle: "Envoyer une meilleure copie ?",
    send: "Envoyer le document",
    sendAnswer: "Envoyer la réponse",
    sentBack: "Motif du refus",
    fromTeam: "Note de l’équipe",
    acceptedHint: "Vérifié et accepté",
    reviewHint: "Nous le vérifions",
    yourAnswer: "Votre réponse",
  },
  share: {
    title: "Envoyer un document",
    short: "Envoyer",
    what: "De quoi s’agit-il ?",
    more: "Plus…",
    other: "Autre",
    which: "Quelle expédition ?",
    noShipment: "Aucune",
    file: "Le fichier",
    note: "Ajouter une note (facultatif)",
    send: "Envoyer",
    sent: "Document envoyé",
  },
  ask: {
    title: "Poser une question",
    short: "Question",
    aboutStep: "Question sur cette étape",
    aboutThis: "Question sur {{step}}",
    chatInstead: "Écrire plutôt à l’équipe",
    quick: {
      when: "Quand sera-ce terminé ?",
      needMe: "Avez-vous besoin de quelque chose de ma part ?",
      faster: "Est-il possible d’accélérer ?",
      other: "Autre chose",
    },
    yourQuestion: "Votre question",
    addDetail: "Un détail à ajouter ? (facultatif)",
    send: "Envoyer la question",
    sent: "Question envoyée à l’équipe",
    yours: "Vos questions",
    question: "Question",
    reply: "Répondre",
    status: {
      OPEN: "Envoyée",
      IN_PROGRESS: "Répondue",
      RESOLVED: "Résolue",
    },
  },
  bill: {
    toPay: "À payer",
    nothingDue: "Tout est réglé",
    ivePaid: "J’ai payé",
    pay: "Payer",
    overdueAmount: "{{amount}} en retard",
    inReviewCount: "En vérification : {{count}}",
    howToPay: "Comment payer",
    howToPayHint:
      "Indiquez le numéro de facture dans le libellé du virement, puis touchez « J’ai payé » et ajoutez le reçu.",
    holder: "Titulaire",
    account: "Numéro de compte",
    iban: "IBAN",
    swift: "SWIFT / BIC",
    filter: "Afficher",
    tab: {
      open: "À payer",
      paid: "Payées",
      payments: "Mes paiements",
    },
    allClear: "Rien à payer",
    noPaid: "Aucune facture payée pour l’instant",
    noProofs: "Aucun paiement envoyé pour l’instant",
    invoice: "Facture",
    invoices: "Factures",
    dueWhen: "Échéance {{when}}",
    wasDue: "Échue {{when}}",
    state: {
      DUE: "À payer",
      OVERDUE: "En retard",
      PART_PAID: "Payée en partie",
      PAID: "Payée",
      IN_REVIEW: "En vérification",
      CANCELLED: "Annulée",
    },
    ofTotal: "sur {{total}}",
    leftToPay: "Reste à payer",
    total: "Total",
    paidAmount: "Payé {{amount}}",
    inReviewAmount: "En vérification {{amount}}",
    issued: "Émise",
    dueOn: "Échéance",
    lines: "Détail",
    atCost: "au coût réel",
    services: "Prestations (HT)",
    disbursements: "Débours",
    vat: "TVA",
    receiptFile: "preuve-de-paiement",
    docs: {
      title: "Justificatifs",
      count: "Justificatifs : {{count}}",
      shared: "Partagés {{when}}",
      all: "Tout télécharger (.zip)",
      show: "Voir les fichiers",
      hide: "Masquer les fichiers",
      downloadOne: "Télécharger {{name}}",
      about: "À propos de ces justificatifs",
      info:
        "Les reçus des frais que cette facture refacture au coût réel. Le ZIP contient la facture et chaque justificatif, numérotés dans l’ordre de ses lignes.",
      zipName: "justificatifs",
    },
    proof: {
      SUBMITTED: "En vérification",
      CONFIRMED: "Confirmé",
      REJECTED: "Non confirmé",
    },
  },
  pay: {
    step1: "Que payez-vous ?",
    step2: "Comment avez-vous payé ?",
    step3: "Ajoutez le reçu",
    progress: "Étape {{step}} sur {{total}}",
    which: "Factures",
    amount: "Montant payé",
    oneCurrency: "Choisissez des factures dans une seule devise.",
    moreThanPicked: "Supérieur aux factures choisies — la comptabilité affectera le reste.",
    how: "Moyen de paiement",
    method: {
      BANK: "Virement",
      MOBILE_MONEY: "Mobile money",
      CASH: "Espèces",
      CHEQUE: "Chèque",
    },
    wallet: "Quel service ?",
    otherWallet: "Autre",
    when: "Quand ?",
    day: {
      today: "Aujourd’hui",
      yesterday: "Hier",
      other: "Autre jour",
    },
    reference: "Référence (facultatif)",
    txId: "ID de transaction (facultatif)",
    chequeNo: "Numéro du chèque (facultatif)",
    note: "Note (facultatif)",
    send: "Envoyer la preuve",
    sent: "Envoyé — la comptabilité va le confirmer",
  },
  quote: {
    request: "Demander un devis",
    new: "Nouveau devis",
    none: "Aucune demande de devis pour l’instant",
    step1: "Quel mode de transport ?",
    step2: "D’où à où ?",
    step3: "Que transportez-vous ?",
    dir: {
      IMPORT: "Import",
      EXPORT: "Export",
      LOCAL: "National",
    },
    from: "Départ",
    to: "Destination",
    sameAsLast: "Comme la dernière fois",
    likeShipment: "Comme {{ref}}",
    describe: "Décrivez-le avec vos mots",
    describeHint: "ex. 2×40HC de carreaux, Shanghai à Douala, FOB, environ 48 t",
    fill: "Remplir pour moi",
    filling: "Lecture de votre description…",
    filled: "C’est rempli — vérifiez chaque étape avant d’envoyer",
    filledPill: "Prérempli",
    tab: {
      requests: "Demandes",
      proposals: "Propositions",
    },
    route: {
      pol: "Port de chargement",
      pod: "Port de déchargement",
      portHint: "Rechercher un port",
      aol: "Aéroport de départ",
      aod: "Aéroport d’arrivée",
      airportHint: "Rechercher un aéroport",
      placeHint: "Ville, port ou adresse",
      collection: "Lieu d’enlèvement",
      collectionAdd: "Nous l’enlevons",
      collectionAddHint: "Chez un fournisseur, une usine ou à toute adresse",
      delivery: "Lieu de livraison",
      deliveryAdd: "Nous le livrons",
      deliveryAddHint: "À votre entrepôt ou à toute adresse",
      doorHint: "Adresse, ville ou entrepôt",
      remove: "Retirer {{place}}",
      doorToDoor: "Porte à porte",
      withCollection: "Enlèvement compris",
      withDelivery: "Livraison comprise",
    },
    incoterm: "Incoterm",
    notSure: "Je ne sais pas",
    what: "De quoi s’agit-il ?",
    whatHint: "ex. 2 palettes de pièces détachées",
    weight: "Poids approximatif (facultatif)",
    send: "Envoyer la demande",
    sent: "Demande envoyée — nous revenons vers vous avec un prix",
    status: {
      RECEIVED: "Reçue",
      UNDER_REVIEW: "En cours de chiffrage",
      CLARIFICATION_REQUIRED: "Précisions requises",
      QUOTED: "Chiffrée",
      CONVERTED_TO_OPPORTUNITY: "En cours",
      CLOSED_NO_ACTION: "Clôturée",
    },
  },
  place: {
    search: "Rechercher",
    clear: "Effacer",
    change: "Modifier",
    recent: "Vos lieux",
    popular: "Les plus fréquents",
    matches: "Ports, aéroports et villes",
    world: "Adresses et lieux dans le monde",
    worldNote: "Nous confirmons l’emplacement exact à l’envoi",
    searchWorld: "Chercher « {{term}} » dans le monde entier",
    searchingWorld: "Recherche d’adresses…",
    searching: "Recherche…",
    useTyped: "Utiliser « {{term}} » tel quel",
    useTypedHint: "Nous le situerons sur la carte pour vous",
    typed: "Tel quel — nous le situerons",
    none: "Aucun résultat pour l’instant",
    unavailable: "La recherche d’adresses est indisponible pour le moment. Écrivez le lieu, nous le situerons.",
    failed: "La recherche n’a pas répondu. Écrivez le lieu, nous le situerons.",
    results: "Lieux trouvés : {{count}}",
    kind: {
      SEAPORT: "Port maritime",
      AIRPORT: "Aéroport",
      TERMINAL: "Terminal",
      RAIL_TERMINAL: "Gare ferroviaire",
      BORDER_POST: "Poste frontière",
      WAREHOUSE: "Entrepôt",
      INLAND: "Port sec",
      CITY: "Ville",
      ADDRESS: "Adresse",
      OTHER: "Lieu",
    },
  },
  prop: {
    proposal: "Proposition",
    status: {
      SENT: "En attente de votre réponse",
      ACCEPTED: "Acceptée",
      REJECTED: "Refusée",
    },
    expired: "Plus valable",
    validUntil: "Valable jusqu’au {{date}}",
    total: "Total",
    pricing: "Tarification",
    accept: "Accepter",
    acceptSign: "Accepter et signer",
    decline: "Refuser",
    acceptTitle: "Accepter cette proposition ?",
    acceptBody:
      "Votre acceptation est enregistrée avec votre nom et l’heure, et l’équipe est prévenue aussitôt.",
    accepted: "Acceptée — merci. L’équipe va vous recontacter.",
    declined: "Refusée — l’équipe va vous recontacter.",
    declineTitle: "Pourquoi refusez-vous ?",
    declineNote: "Autre chose à ajouter ? (facultatif)",
    declineSend: "Refuser la proposition",
    awaiting: "Une proposition attend votre réponse",
    awaitingCount: "En attente : {{count}}",
    review: "Voir",
    sign: {
      step1: "Confirmez votre identité",
      step2: "Signez",
      sending: "Envoi d’un code…",
      sentTo: "Nous avons envoyé un code à 6 chiffres à {{email}}.",
      codeLabel: "Code de signature",
      resend: "Renvoyer un code",
      resent: "Un nouveau code est en route",
      how: "Comment voulez-vous signer ?",
      card: {
        STAMP: "Cachet à mon nom",
        DRAWN: "Dessiner ma signature",
      },
      name: "Votre nom",
      role: "Votre fonction (facultatif)",
      rolePlaceholder: "Directrice financière",
      draw: "Signez ici",
      clear: "Effacer",
      agree: "Signer vaut acceptation de cette proposition et de ses conditions.",
      aboutTitle: "À propos de cette signature",
      about:
        "Votre e-mail est confirmé par le code ; votre nom et votre fonction sont tels que vous les avez saisis. Les deux figurent sur le certificat de signature, que tout détenteur du document peut vérifier avec son code.",
      submit: "Signer et accepter",
      signedBy: "Signée par {{name}}",
      verify: "Code de vérification",
    },
  },
  docs: {
    filter: "Afficher",
    toSend: "À envoyer",
    sent: "Envoyés",
    library: "Bibliothèque",
    nothingToSend: "Rien à envoyer — tout est fait",
    nothingSent: "Rien d’envoyé pour l’instant",
    none: "Aucun document pour l’instant",
    search: "Rechercher un document",
    general: "Documents de l’entreprise",
    document: "Document",
  },
  team: {
    title: "Équipe",
    invite: "Inviter",
    inviteTitle: "Inviter un collègue",
    name: "Nom",
    nameHint: "Pour les accueillir ; il apparaît sur chaque message et fichier qu’ils envoient.",
    access: "Accès",
    scope: {
      ALL: "Tout",
      OPERATIONS: "Expéditions et documents",
      BILLING: "Facturation",
    },
    scopeHint: {
      ALL: "Expéditions, documents et facturation",
      OPERATIONS: "Sans factures ni paiements",
      BILLING: "Factures et paiements uniquement",
    },
    makeAdmin: "Peut gérer l’équipe",
    adminHint: "Inviter, modifier et retirer des collègues",
    admin: "Admin",
    sendInvite: "Envoyer l’invitation",
    inviteSent: "Invitation envoyée à {{email}}",
    invited: "Invité",
    you: "Vous",
    saved: "Enregistré",
    remove: "Retirer de l’équipe",
    removeTitle: "Retirer {{name}} ?",
    removeBody: "L’accès est retiré immédiatement. Vous pourrez inviter cette personne à nouveau plus tard.",
    removed: "Retiré de l’équipe",
  },
  account: {
    editName: "Modifier votre nom",
    nameTitle: "Votre nom",
    nameLabel: "Nom complet",
    nameBody: "Il vous accueille ici et apparaît sur chaque message, document et paiement que vous envoyez, pour que l’équipe sache à qui elle parle.",
    nameSaved: "Nom enregistré",
    addName: "Ajouter votre nom",
    security: "Sécurité",
    device: "Appareil",
    thisDevice: "Cet appareil",
    lastSeen: "Vu {{when}}",
    signOutDevice: "Déconnecter",
    deviceOutTitle: "Déconnecter cet appareil ?",
    deviceOut: "Appareil déconnecté",
    preferences: "Préférences",
    language: "Langue",
    theme: "Apparence",
    light: "Clair",
    dark: "Sombre",
    auto: "Auto",
    signOut: "Se déconnecter",
    signOutForget: "Se déconnecter et oublier cet appareil",
    signOutTitle: "Se déconnecter ?",
    forgetTitle: "Oublier cet appareil ?",
    forgetBody: "La prochaine fois, vous repartirez de votre e-mail.",
    portal: "Portail",
  },
  notify: {
    title: "Notifications",
    thisDevice: "Cet appareil",
    state: {
      on: "Activées — nous vous prévenons ici",
      off: "Désactivées",
      blocked: "Bloquées pour ce site",
      unsupported: "Indisponibles dans ce navigateur",
      installFirst: "Ajoutez d’abord le portail à votre écran d’accueil",
      unconfigured: "Pas encore disponibles",
    },
    switchLabel: "Notifications sur cet appareil",
    turnedOn: "Notifications activées",
    turnedOff: "Notifications désactivées sur cet appareil",
    test: "Envoyer un test",
    testSent: "Test envoyé — regardez vos notifications",
    testNone: "Aucun appareil n’a répondu — désactivez puis réactivez les notifications",
    email: "E-mail",
    push: "Appli",
    topic: {
      MESSAGES: "Messages de l’équipe",
      REQUESTS: "Documents demandés",
      BILLING: "Factures et paiements",
      PROPOSALS: "Propositions",
      SHIPMENTS: "Étapes d’expédition",
    },
    saved: "Enregistré",
    infoLabel: "Fonctionnement des notifications",
    infoTitle: "Comment nous vous prévenons",
    info1:
      "Dans l’appli, dès qu’une chose vous attend : une réponse, un document demandé, une nouvelle facture ou proposition, une expédition qui avance.",
    info2:
      "Par e-mail, une réponse seulement si elle n’est pas lue dix minutes plus tard — au plus une fois par heure et par conversation.",
    info3: "Les étapes d’expédition par e-mail sont désactivées au départ. Activez-les si vous le souhaitez.",
    blockedTitle: "Les notifications sont bloquées",
    blockedHow:
      "Elles ont été refusées pour ce site. Autorisez-les dans les réglages du site — le cadenas à côté de l’adresse — puis revenez ici.",
  },
  install: {
    title: "Installer l’application",
    hint: "S’ouvre comme une application, avec notifications",
    button: "Installer",
    done: "Installée",
    howLabel: "Comment installer",
    iosTitle: "Ajouter à l’écran d’accueil",
    ios1: "Touchez le bouton Partager dans Safari.",
    ios2: "Choisissez « Sur l’écran d’accueil ».",
    ios3: "Ouvrez le portail depuis sa nouvelle icône, puis activez les notifications ici.",
  },
  fin: {
    title: "Situation financière",
    period: "{{from}} – {{to}} · OHADA",
    revenue: "Chiffre d’affaires",
    netResult: "Résultat net",
    cash: "Trésorerie",
    bsTotal: "Total du bilan",
    incomeStatement: "Compte de résultat",
    produits: "Produits",
    charges: "Charges",
    hao: "Hors activités ordinaires (net)",
    balanceSheet: "Bilan",
    actif: "Actif",
    passif: "Passif",
    result: "Résultat",
    total: "Total",
    unbalanced:
      "L’actif et le passif ne s’équilibrent pas sur cette période — les chiffres sont provisoires.",
    cashPosition: "Trésorerie par compte",
    noTreasury: "Aucun compte de trésorerie",
  },
  audit: {
    title: "Salle d’audit",
    until: "Accès jusqu’au {{date}}",
    trialBalance: "Balance générale",
    account: "Compte",
    debit: "Débit",
    credit: "Crédit",
    noMovements: "Aucun mouvement sur la période",
    trail: "Piste d’audit",
    noPostings: "Aucune écriture sur la période",
    system: "Système",
    dataRoom: "Salle de données",
    ask: "Demander un document",
    what: "De quoi avez-vous besoin, pour quelle période ou quel dossier ?",
    send: "Envoyer la demande",
    asked: "Demande envoyée",
    noRequests: "Aucune demande pour l’instant",
    noDocs: "Aucun document partagé pour l’instant",
    room: {
      OPEN: "En attente",
      ANSWERED: "Traitée",
    },
  },
} as const;
