/**
 * Test stub for `virtual:pwa-register/react`.
 *
 * The real module is generated by vite-plugin-pwa, which vitest.config.ts
 * deliberately does not load (see the note there — the PWA plugin and the
 * manualChunks strategy have no business running in tests). Without something
 * to resolve, any test that renders a component importing the virtual module
 * fails at import-analysis before `vi.mock` gets a chance to intervene.
 *
 * Tests mock this specifier to script the update lifecycle; this file exists so
 * the specifier resolves at all. It is never expected to run.
 */
export function useRegisterSW(): {
  offlineReady: [boolean, (v: boolean) => void];
  needRefresh: [boolean, (v: boolean) => void];
  updateServiceWorker: (reloadPage?: boolean) => Promise<void>;
} {
  throw new Error(
    "virtual:pwa-register/react stub was called — the test should vi.mock() this module.",
  );
}
