"use strict";
const service = require("./financial_dictionary.service");
const validator = require("./financial_dictionary.validator");
const rateValidator = require("./financial_dictionary.rate.validator");
module.exports = {
  entity: "dictionary_item", module_key: "MOD-05", screens: [],
  reads: [
    { key: "list_dictionary_items", service: service.listItems, permission: { module: "MOD-05", action: "view" }, describe: "List financial dictionary items (services, débours, overheads)." },
    { key: "get_dictionary_item", service: service.get, permission: { module: "MOD-05", action: "view" }, describe: "Get a dictionary item with its posting rules. `default_price` is its STANDARD expense rate in force today (no carrier, no container type) — the item's only price." },
    // Where a line is used — the rows behind the 360's usage tiles, a page at a
    // time. One read per document kind, each gated on the module that owns
    // those documents (the HTTP route checks the same grants). The invoice read
    // is finals and credit notes (MOD-51); proformas are MOD-50's.
    { key: "dictionary_item_costing_lines", service: (c, p) => service.listUsage(c, p.dictionary_item_id, "costings", p), permission: { module: "MOD-46", action: "view" }, describe: "The costing-sheet lines that use a dictionary item, newest first, with the costing number, status, operations file ref, client and amount. Params: dictionary_item_id, limit (≤100), offset. Returns { rows, total }." },
    { key: "dictionary_item_cash_request_lines", service: (c, p) => service.listUsage(c, p.dictionary_item_id, "cash_requests", p), permission: { module: "MOD-49", action: "view" }, describe: "The cash-request lines that use a dictionary item, newest first, with the request number, status, operations file ref, client and budget amount. Params: dictionary_item_id, limit (≤100), offset. Returns { rows, total }." },
    { key: "dictionary_item_invoice_lines", service: (c, p) => service.listUsage(c, p.dictionary_item_id, "invoices", p, { invoiceTypes: ["FINAL", "CREDIT_NOTE"] }), permission: { module: "MOD-51", action: "view" }, describe: "The final-invoice and credit-note lines that use a dictionary item, newest first, with the invoice number, type, status, operations file ref, client and amount. Params: dictionary_item_id, limit (≤100), offset. Returns { rows, total }." },
    { key: "dictionary_item_purchase_order_lines", service: (c, p) => service.listUsage(c, p.dictionary_item_id, "purchase_orders", p), permission: { module: "MOD-60", action: "view" }, describe: "The purchase-order lines that use a dictionary item, newest first, with the PO number, status, operations file ref, supplier and amount. Params: dictionary_item_id, limit (≤100), offset. Returns { rows, total }." },
    { key: "dictionary_item_spend_documents", service: (c, p) => service.spendDocumentsPage(c, p.dictionary_item_id, p), permission: { module: "MOD-05", action: "view" }, describe: "The documents behind a dictionary item's spend over a period: costing lines (estimated), open PO and approved cash-request lines (committed) and ledger cost entries (actual), newest first. Params: dictionary_item_id, from / to (YYYY-MM-DD, default the trailing 12 months), lens ('estimated' | 'committed' | 'actual', optional — every lens when absent), dossier_id (optional), limit (≤100), offset. Returns { rows, total }." },
    { key: "dictionary_item_siblings", service: (c, p) => service.siblingsFor(c, p.ids || (p.dictionary_item_id ? [p.dictionary_item_id] : [])), permission: { module: "MOD-05", action: "view" }, describe: "For dictionary lines, the other fulfilment modes of the same service (débours 'billed to the client at cost', 'our own cost', 'a deposit we lodge', 'our own service'), so the right row is chosen for a document. Params: ids (array of dictionary_item_id) or dictionary_item_id. Returns { [id]: { mode, sibling_group, siblings } }." },
    { key: "dictionary_lines_to_pair", service: (c) => service.unpairedLines(c), permission: { module: "MOD-05", action: "view" }, describe: "Dictionary lines named as one fulfilment mode of a service ('— Client Account', '— Own Cost', '— Deposit') that are not linked to the service's other modes, or whose name contradicts their direction — for a person to pair." },
    // A READ: it returns a suggestion and saves nothing — creating or changing
    // a line's posting stays a person's act (meeting 6, F3). It may make a
    // metered grounded call, under the feature's own gate and budget.
    { key: "suggest_dictionary_posting", service: (c, p, actor) => service.suggestPosting(c, { label_fr: p.label_fr, label_en: p.label_en, category: p.category, direction: p.direction }, actor), permission: { module: "MOD-05", action: "create" }, describe: "Suggest the generic SYSCOHADA posting of a financial-dictionary line from its name, category and (optional) direction: direction, débours flag, VAT treatment and posting rules mapped onto this tenant's accounts, with a confidence level and where it came from (shared cache, web search, or the local suggestion without a web search). Params: label_fr, label_en?, category (disbursement|service|overhead|asset|other), direction? (REVENUE|EXPENSE|DISBURSEMENT|ASSET). Saves nothing." },
    { key: "dictionary_posting_review", service: (c) => service.latestReview(c), permission: { module: "MOD-05", action: "view" }, describe: "The latest review of the dictionary's postings against the AI suggestion: the run's progress and every line whose posting differs, with the reasons. The review changes nothing." },
    { key: "dictionary_rate_history", service: (c, p) => service.rateEvolution(c, p.dictionary_item_id, { as_of: p.as_of }), permission: { module: "MOD-05", action: "view" }, describe: "The effective-dated rate history of a dictionary item, one series per carrier / container type, with the rate in force and its trend. Params: dictionary_item_id, as_of (YYYY-MM-DD, optional)." },
  ],
  writes: [
    // A price on create is opened as the item's standard expense rate, so it is
    // a MOD-10 write too — the HTTP route checks that; here the price is left
    // off and set through set_dictionary_rate, which carries the MOD-10 gate.
    { key: "create_dictionary_item", service: (c, p, actor) => service.create(c, { data: { ...p, default_price: undefined }, actor }), schema: validator.schemas.create, permission: { module: "MOD-05", action: "create" }, confirm: true, describe: "Create a dictionary item with ≥1 posting rule (KB §4). The code is minted from the direction (R/E/D/A + lowest free number). Set its price afterwards with set_dictionary_rate. client_heading_ref_id picks the client-facing family (a dictionary_ref of kind CLIENT_HEADING) it prints under on quotations and invoices." },
    { key: "update_dictionary_item", service: (c, p, actor) => (({ dictionary_item_id, ...patch }) => service.update(c, { id: dictionary_item_id, patch, actor }))(p), schema: validator.schemas.aiUpdate, permission: { module: "MOD-05", action: "edit" }, confirm: true, describe: "Edit a dictionary item and (optionally) replace its posting rules. Changing `direction` moves the code to the new letter's lowest free number. Cannot change the price — use set_dictionary_rate." },
    { key: "set_dictionary_rate", service: (c, p, actor) => (({ dictionary_item_id, ...data }) => service.supersedeRate(c, { id: dictionary_item_id, data, actor }))(p), schema: rateValidator.schemas.aiRateSupersede, permission: { module: "MOD-10", action: "edit" }, confirm: true, describe: "Set a dictionary item's rate from a date: its standard rate (no rate_provider_id / container_type_ref_id) or one carrier / container-type series. The open rate is expired the day before; history is never edited. Currency defaults to the tenant's base currency. rate is HT unless price_includes_vat is true: then it is the TTC price and the HT is stored (TTC ÷ (1 + the line's VAT rate)); never on a débours." },
    { key: "link_dictionary_sibling", service: (c, p, actor) => service.linkSibling(c, { id: p.dictionary_item_id, linkTo: p.link_to || null, standsAlone: p.stands_alone === true, actor }), schema: validator.schemas.aiSiblingLink, permission: { module: "MOD-05", action: "edit" }, confirm: true, describe: "Link a dictionary line to another line of the same service in a different fulfilment mode (link_to), or confirm it stands alone (stands_alone: true). A service holds one line per mode; codes and posting rules do not change." },
    { key: "apply_dictionary_rate_to_carriers", service: (c, p, actor) => (({ dictionary_item_id, ...data }) => service.applyRateToProviders(c, { id: dictionary_item_id, data, actor }))(p), schema: rateValidator.schemas.aiRateApplyAll, permission: { module: "MOD-10", action: "edit" }, confirm: true, describe: "Apply ONE rate from a date to several carriers of a dictionary item at once (rate_provider_ids), optionally for one container type. All or nothing: if any carrier already has a rate starting on or after that date, nothing is saved." },
  ],
};
